package bwsi.PumpOperations;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.BALayout;
import anywheresoftware.b4a.debug.*;

public class globalvar {
private static globalvar mostCurrent = new globalvar();
public static Object getObject() {
    throw new RuntimeException("Code module does not support this method.");
}
 public anywheresoftware.b4a.keywords.Common __c = null;
public static int _dbversion = 0;
public static String _serveraddress = "";
public static String _apicontroller = "";
public static String _baseurl = "";
public static anywheresoftware.b4a.objects.CSBuilder _cstitle = null;
public static anywheresoftware.b4a.objects.CSBuilder _cssubtitle = null;
public static double _pricolor = 0;
public static double _seccolor = 0;
public static double _poscolor = 0;
public static double _negcolor = 0;
public static double _neutralcolor = 0;
public static double _bluecolor = 0;
public static double _greencolor = 0;
public static double _greencolor2 = 0;
public static double _redcolor = 0;
public static double _yellowcolor = 0;
public static double _graycolor = 0;
public static adr.stringfunctions.stringfunctions _sf = null;
public static int _userid = 0;
public static String _username = "";
public static String _userpw = "";
public static String _useravatar = "";
public static String _empname = "";
public static int _userposid = 0;
public static String _userpos = "";
public static int _branchid = 0;
public static String _branchcode = "";
public static String _branchname = "";
public static int _sysmode = 0;
public static String _rdgfrom = "";
public static String _rdgto = "";
public static String _trandate = "";
public static int _pumphouseid = 0;
public static String _pumphousecode = "";
public static String _pumpdrainpipetype = "";
public static String _pumpdrainpipesize = "";
public static int _tranheaderid = 0;
public static boolean _blnnewtime = false;
public static int _timedetailid = 0;
public static long _selectedpumptime = 0L;
public static boolean _blnnewfmrdg = false;
public static int _fmrdgdetailid = 0;
public static boolean _blnnewpsirdg = false;
public static int _psirdgdetailid = 0;
public static boolean _blnnewchlorine = false;
public static int _chlorinedetailid = 0;
public static boolean _blnnewproblem = false;
public static int _problemdetailid = 0;
public static boolean _blnnewpsidist = false;
public static int _psidistdetailid = 0;
public static boolean _blnnewnonop = false;
public static int _nonopdetailid = 0;
public static int _selectedjoid = 0;
public static int _selectedjocat = 0;
public static String _selectedjocatcode = "";
public static String _selectedjodesc = "";
public static String _selectedjoreason = "";
public static boolean _blnnewgpm = false;
public static int _gpmid = 0;
public static int _repmainid = 0;
public static String _repmaindesc = "";
public static String _lat = "";
public static String _lon = "";
public static double _speed = 0;
public static String _sat = "";
public static String _gnssstats = "";
public static boolean _readstoragepermission = false;
public static boolean _writestoragepermission = false;
public static boolean _coarselocpermission = false;
public static boolean _finelocpermission = false;
public b4a.example.dateutils _dateutils = null;
public bwsi.PumpOperations.main _main = null;
public bwsi.PumpOperations.actnewproduction _actnewproduction = null;
public bwsi.PumpOperations.addedittimerecord _addedittimerecord = null;
public bwsi.PumpOperations.mainscreen _mainscreen = null;
public bwsi.PumpOperations.actcmjofindings _actcmjofindings = null;
public bwsi.PumpOperations.actcriticalpoint _actcriticalpoint = null;
public bwsi.PumpOperations.actdccrjofindings _actdccrjofindings = null;
public bwsi.PumpOperations.actdcdajofindings _actdcdajofindings = null;
public bwsi.PumpOperations.actdebugkeyboard _actdebugkeyboard = null;
public bwsi.PumpOperations.actgpmcalc _actgpmcalc = null;
public bwsi.PumpOperations.actgpmhistory _actgpmhistory = null;
public bwsi.PumpOperations.actjo _actjo = null;
public bwsi.PumpOperations.actjoaccomplishedsas _actjoaccomplishedsas = null;
public bwsi.PumpOperations.actjodetails _actjodetails = null;
public bwsi.PumpOperations.actjonotification _actjonotification = null;
public bwsi.PumpOperations.actjoreasons _actjoreasons = null;
public bwsi.PumpOperations.actjosummary _actjosummary = null;
public bwsi.PumpOperations.actjowithreasons _actjowithreasons = null;
public bwsi.PumpOperations.actmcjofindings _actmcjofindings = null;
public bwsi.PumpOperations.actncjofindings _actncjofindings = null;
public bwsi.PumpOperations.actnonoperational _actnonoperational = null;
public bwsi.PumpOperations.actproduction _actproduction = null;
public bwsi.PumpOperations.actpumpoff _actpumpoff = null;
public bwsi.PumpOperations.actrcjofindings _actrcjofindings = null;
public bwsi.PumpOperations.actrepmain _actrepmain = null;
public bwsi.PumpOperations.actsasjofindings _actsasjofindings = null;
public bwsi.PumpOperations.actwaterbalance _actwaterbalance = null;
public bwsi.PumpOperations.addeditchlorinerecord _addeditchlorinerecord = null;
public bwsi.PumpOperations.addeditfmrdg _addeditfmrdg = null;
public bwsi.PumpOperations.addeditnonoperational _addeditnonoperational = null;
public bwsi.PumpOperations.addeditproblem _addeditproblem = null;
public bwsi.PumpOperations.addeditpsidistrecord _addeditpsidistrecord = null;
public bwsi.PumpOperations.addeditpsirdg _addeditpsirdg = null;
public bwsi.PumpOperations.dbasefunctions _dbasefunctions = null;
public bwsi.PumpOperations.dbutils _dbutils = null;
public bwsi.PumpOperations.edittimerecord _edittimerecord = null;
public bwsi.PumpOperations.firebasemessaging _firebasemessaging = null;
public bwsi.PumpOperations.miscfunctions _miscfunctions = null;
public bwsi.PumpOperations.myfunctions _myfunctions = null;
public bwsi.PumpOperations.myscale _myscale = null;
public bwsi.PumpOperations.starter _starter = null;
public bwsi.PumpOperations.validation _validation = null;
public bwsi.PumpOperations.httputils2service _httputils2service = null;
public bwsi.PumpOperations.b4xcollections _b4xcollections = null;
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 1;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 2;BA.debugLine="Public DBVersion As Int";
_dbversion = 0;
 //BA.debugLineNum = 3;BA.debugLine="Public ServerAddress As String";
_serveraddress = "";
 //BA.debugLineNum = 4;BA.debugLine="Public APIController As String = \"ApiController\"";
_apicontroller = "ApiController";
 //BA.debugLineNum = 5;BA.debugLine="Public BaseURL As String = \"https://bowa-api.bwsi";
_baseurl = "https://bowa-api.bwsi.com.ph/api/";
 //BA.debugLineNum = 7;BA.debugLine="Public CSTitle As CSBuilder";
_cstitle = new anywheresoftware.b4a.objects.CSBuilder();
 //BA.debugLineNum = 8;BA.debugLine="Public CSSubtitle As CSBuilder";
_cssubtitle = new anywheresoftware.b4a.objects.CSBuilder();
 //BA.debugLineNum = 10;BA.debugLine="Public PriColor = 0xFF007BFF As Double 'primary";
_pricolor = 0xff007bff;
 //BA.debugLineNum = 11;BA.debugLine="Public SecColor = 0xFF7FBDFF As Double";
_seccolor = 0xff7fbdff;
 //BA.debugLineNum = 13;BA.debugLine="Public PosColor = 0xFF007BFF As Double";
_poscolor = 0xff007bff;
 //BA.debugLineNum = 14;BA.debugLine="Public NegColor = 0xFFDC3545 As Double";
_negcolor = 0xffdc3545;
 //BA.debugLineNum = 15;BA.debugLine="Public NeutralColor = 0xFF7FBDFF As Double";
_neutralcolor = 0xff7fbdff;
 //BA.debugLineNum = 17;BA.debugLine="Public BlueColor = 0xFF17A2B7 As Double 'info col";
_bluecolor = 0xff17a2b7;
 //BA.debugLineNum = 18;BA.debugLine="Public GreenColor = 0xFF28A745 As Double 'success";
_greencolor = 0xff28a745;
 //BA.debugLineNum = 19;BA.debugLine="Public GreenColor2 = 0xFF188731 As Double 'succes";
_greencolor2 = 0xff188731;
 //BA.debugLineNum = 20;BA.debugLine="Public RedColor = 0xFFDC3545 As Double 'danger co";
_redcolor = 0xffdc3545;
 //BA.debugLineNum = 21;BA.debugLine="Public YellowColor = 0xFFFFC107 As Double 'warnin";
_yellowcolor = 0xffffc107;
 //BA.debugLineNum = 22;BA.debugLine="Public GrayColor = 0xFF62789E As Double";
_graycolor = 0xff62789e;
 //BA.debugLineNum = 24;BA.debugLine="Public SF As StringFunctions";
_sf = new adr.stringfunctions.stringfunctions();
 //BA.debugLineNum = 26;BA.debugLine="Public UserID As Int";
_userid = 0;
 //BA.debugLineNum = 27;BA.debugLine="Public UserName As String";
_username = "";
 //BA.debugLineNum = 28;BA.debugLine="Public UserPW As String";
_userpw = "";
 //BA.debugLineNum = 29;BA.debugLine="Public UserAvatar As String";
_useravatar = "";
 //BA.debugLineNum = 30;BA.debugLine="Public EmpName As String";
_empname = "";
 //BA.debugLineNum = 31;BA.debugLine="Public UserPosID As Int";
_userposid = 0;
 //BA.debugLineNum = 32;BA.debugLine="Public UserPos As String";
_userpos = "";
 //BA.debugLineNum = 34;BA.debugLine="Public BranchID As Int";
_branchid = 0;
 //BA.debugLineNum = 35;BA.debugLine="Public BranchCode As String";
_branchcode = "";
 //BA.debugLineNum = 36;BA.debugLine="Public BranchName As String";
_branchname = "";
 //BA.debugLineNum = 37;BA.debugLine="Public SysMode As Int";
_sysmode = 0;
 //BA.debugLineNum = 39;BA.debugLine="Public RdgFrom, RdgTo As String";
_rdgfrom = "";
_rdgto = "";
 //BA.debugLineNum = 40;BA.debugLine="Public TranDate As String";
_trandate = "";
 //BA.debugLineNum = 41;BA.debugLine="Public PumpHouseID As Int";
_pumphouseid = 0;
 //BA.debugLineNum = 42;BA.debugLine="Public PumpHouseCode As String";
_pumphousecode = "";
 //BA.debugLineNum = 43;BA.debugLine="Public PumpDrainPipeType As String";
_pumpdrainpipetype = "";
 //BA.debugLineNum = 44;BA.debugLine="Public PumpDrainPipeSize As String";
_pumpdrainpipesize = "";
 //BA.debugLineNum = 46;BA.debugLine="Public TranHeaderID As Int";
_tranheaderid = 0;
 //BA.debugLineNum = 49;BA.debugLine="Public blnNewTime As Boolean";
_blnnewtime = false;
 //BA.debugLineNum = 50;BA.debugLine="Public TimeDetailID As Int";
_timedetailid = 0;
 //BA.debugLineNum = 51;BA.debugLine="Public SelectedPumpTime As Long";
_selectedpumptime = 0L;
 //BA.debugLineNum = 54;BA.debugLine="Public blnNewFMRdg As Boolean";
_blnnewfmrdg = false;
 //BA.debugLineNum = 55;BA.debugLine="Public FMRdgDetailID As Int";
_fmrdgdetailid = 0;
 //BA.debugLineNum = 58;BA.debugLine="Public blnNewPSIRdg As Boolean";
_blnnewpsirdg = false;
 //BA.debugLineNum = 59;BA.debugLine="Public PSIRdgDetailID As Int";
_psirdgdetailid = 0;
 //BA.debugLineNum = 62;BA.debugLine="Public blnNewChlorine As Boolean";
_blnnewchlorine = false;
 //BA.debugLineNum = 63;BA.debugLine="Public ChlorineDetailID As Int";
_chlorinedetailid = 0;
 //BA.debugLineNum = 66;BA.debugLine="Public blnNewProblem As Boolean";
_blnnewproblem = false;
 //BA.debugLineNum = 67;BA.debugLine="Public ProblemDetailID As Int";
_problemdetailid = 0;
 //BA.debugLineNum = 70;BA.debugLine="Public blnNewPSIDist As Boolean";
_blnnewpsidist = false;
 //BA.debugLineNum = 71;BA.debugLine="Public PSIDistDetailID As Int";
_psidistdetailid = 0;
 //BA.debugLineNum = 74;BA.debugLine="Public blnNewNonOp As Boolean";
_blnnewnonop = false;
 //BA.debugLineNum = 75;BA.debugLine="Public NonOpDetailID As Int";
_nonopdetailid = 0;
 //BA.debugLineNum = 77;BA.debugLine="Public SelectedJOID As Int";
_selectedjoid = 0;
 //BA.debugLineNum = 78;BA.debugLine="Public SelectedJOCat As Int";
_selectedjocat = 0;
 //BA.debugLineNum = 79;BA.debugLine="Public SelectedJOCatCode As String";
_selectedjocatcode = "";
 //BA.debugLineNum = 80;BA.debugLine="Public SelectedJODesc As String";
_selectedjodesc = "";
 //BA.debugLineNum = 81;BA.debugLine="Public SelectedJOReason As String";
_selectedjoreason = "";
 //BA.debugLineNum = 84;BA.debugLine="Public blnNewGPM As Boolean";
_blnnewgpm = false;
 //BA.debugLineNum = 85;BA.debugLine="Public GPMId As Int";
_gpmid = 0;
 //BA.debugLineNum = 87;BA.debugLine="Public RepMainID As Int";
_repmainid = 0;
 //BA.debugLineNum = 88;BA.debugLine="Public RepMainDesc As String";
_repmaindesc = "";
 //BA.debugLineNum = 91;BA.debugLine="Public Lat, Lon As String";
_lat = "";
_lon = "";
 //BA.debugLineNum = 92;BA.debugLine="Public Speed As Double";
_speed = 0;
 //BA.debugLineNum = 93;BA.debugLine="Public Sat As String";
_sat = "";
 //BA.debugLineNum = 94;BA.debugLine="Public GNSSStats As String";
_gnssstats = "";
 //BA.debugLineNum = 97;BA.debugLine="Public ReadStoragePermission As Boolean";
_readstoragepermission = false;
 //BA.debugLineNum = 98;BA.debugLine="Public WriteStoragePermission As Boolean";
_writestoragepermission = false;
 //BA.debugLineNum = 99;BA.debugLine="Public CoarseLocPermission As Boolean";
_coarselocpermission = false;
 //BA.debugLineNum = 100;BA.debugLine="Public FineLocPermission As Boolean";
_finelocpermission = false;
 //BA.debugLineNum = 101;BA.debugLine="End Sub";
return "";
}
}
