package bwsi.PumpOperations.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_ncjofindings{

public static void LS_general(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
anywheresoftware.b4a.keywords.LayoutBuilder.scaleAll(views);
views.get("pnlmain").vw.setLeft((int)(0d));
views.get("pnlmain").vw.setTop((int)((0.5d / 100 * height)));
views.get("pnlmain").vw.setHeight((int)((195d / 100 * height) - ((0.5d / 100 * height))));
views.get("pnlmain").vw.setWidth((int)((100d / 100 * width)));
views.get("pnljodetails").vw.setTop((int)((1d / 100 * height)));
views.get("pnljodetails").vw.setHeight((int)((52d / 100 * height)));
views.get("pnljodetails").vw.setLeft((int)((1d / 100 * width)));
views.get("pnljodetails").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("lbljodetailstitle").vw.setLeft((int)((0d / 100 * width)));
views.get("lbljodetailstitle").vw.setWidth((int)((views.get("pnljodetails").vw.getWidth()) - ((0d / 100 * width))));
views.get("lbljodetailstitle").vw.setLeft((int)((0d / 100 * width)));
views.get("lbljodetailstitle").vw.setWidth((int)((views.get("pnljodetails").vw.getWidth()) - ((0d / 100 * width))));
views.get("lblcaption1").vw.setTop((int)((views.get("lbljodetailstitle").vw.getTop() + views.get("lbljodetailstitle").vw.getHeight())+(5d * scale)));
views.get("pnljodetstyle1").vw.setTop((int)((views.get("lbljodetailstitle").vw.getTop() + views.get("lbljodetailstitle").vw.getHeight())+(5d * scale)));
views.get("pnljodetstyle1").vw.setLeft((int)((views.get("lblcaption1").vw.getLeft() + views.get("lblcaption1").vw.getWidth())+(2d * scale)));
views.get("pnljodetstyle1").vw.setWidth((int)((views.get("pnljodetails").vw.getWidth())-(2d / 100 * width) - ((views.get("lblcaption1").vw.getLeft() + views.get("lblcaption1").vw.getWidth())+(2d * scale))));
views.get("lbljonum").vw.setLeft((int)((2d / 100 * width)));
views.get("lbljonum").vw.setWidth((int)((views.get("pnljodetstyle1").vw.getWidth())-(1d / 100 * width) - ((2d / 100 * width))));
views.get("lbljonum").vw.setTop((int)((0.25d / 100 * height)));
views.get("lbljonum").vw.setHeight((int)((views.get("pnljodetstyle1").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("pnljodetstyle2").vw.setTop((int)((views.get("pnljodetstyle1").vw.getTop() + views.get("pnljodetstyle1").vw.getHeight())+(1d * scale)));
views.get("pnljodetstyle2").vw.setLeft((int)((views.get("lblcaption1").vw.getLeft() + views.get("lblcaption1").vw.getWidth())+(2d * scale)));
views.get("pnljodetstyle2").vw.setWidth((int)((views.get("pnljodetails").vw.getWidth())-(2d / 100 * width) - ((views.get("lblcaption1").vw.getLeft() + views.get("lblcaption1").vw.getWidth())+(2d * scale))));
views.get("lbljocat").vw.setLeft((int)((2d / 100 * width)));
views.get("lbljocat").vw.setWidth((int)((views.get("pnljodetstyle2").vw.getWidth())-(1d / 100 * width) - ((2d / 100 * width))));
views.get("lbljocat").vw.setTop((int)((0.25d / 100 * height)));
views.get("lbljocat").vw.setHeight((int)((views.get("pnljodetstyle2").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("lblcaption2").vw.setTop((int)((views.get("pnljodetstyle2").vw.getTop() + views.get("pnljodetstyle2").vw.getHeight())+(3d * scale)));
views.get("pnljodetstyle3").vw.setTop((int)((views.get("pnljodetstyle2").vw.getTop() + views.get("pnljodetstyle2").vw.getHeight())+(3d * scale)));
views.get("pnljodetstyle3").vw.setLeft((int)((views.get("lblcaption2").vw.getLeft() + views.get("lblcaption2").vw.getWidth())+(2d * scale)));
views.get("pnljodetstyle3").vw.setWidth((int)((views.get("pnljodetails").vw.getWidth())-(2d / 100 * width) - ((views.get("lblcaption2").vw.getLeft() + views.get("lblcaption2").vw.getWidth())+(2d * scale))));
views.get("lblappnum").vw.setLeft((int)((2d / 100 * width)));
views.get("lblappnum").vw.setWidth((int)((views.get("pnljodetstyle3").vw.getWidth())-(1d / 100 * width) - ((2d / 100 * width))));
views.get("lblappnum").vw.setTop((int)((0.25d / 100 * height)));
views.get("lblappnum").vw.setHeight((int)((views.get("pnljodetstyle3").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("lblcaption3").vw.setTop((int)((views.get("pnljodetstyle3").vw.getTop() + views.get("pnljodetstyle3").vw.getHeight())+(3d * scale)));
views.get("pnljodetstyle4").vw.setTop((int)((views.get("pnljodetstyle3").vw.getTop() + views.get("pnljodetstyle3").vw.getHeight())+(3d * scale)));
views.get("pnljodetstyle4").vw.setLeft((int)((views.get("lblcaption3").vw.getLeft() + views.get("lblcaption3").vw.getWidth())+(2d * scale)));
views.get("pnljodetstyle4").vw.setWidth((int)((views.get("pnljodetails").vw.getWidth())-(2d / 100 * width) - ((views.get("lblcaption3").vw.getLeft() + views.get("lblcaption3").vw.getWidth())+(2d * scale))));
views.get("lblcustname").vw.setLeft((int)((2d / 100 * width)));
views.get("lblcustname").vw.setWidth((int)((views.get("pnljodetstyle4").vw.getWidth())-(1d / 100 * width) - ((2d / 100 * width))));
views.get("lblcustname").vw.setTop((int)((0.25d / 100 * height)));
views.get("lblcustname").vw.setHeight((int)((views.get("pnljodetstyle4").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("pnljodetstyle5").vw.setTop((int)((views.get("pnljodetstyle4").vw.getTop() + views.get("pnljodetstyle4").vw.getHeight())+(3d * scale)));
views.get("pnljodetstyle5").vw.setLeft((int)((views.get("lblcaption1").vw.getLeft())));
views.get("pnljodetstyle5").vw.setWidth((int)((views.get("pnljodetails").vw.getWidth())-(2d / 100 * width) - ((views.get("lblcaption1").vw.getLeft()))));
views.get("lblcustaddress").vw.setLeft((int)((2d / 100 * width)));
views.get("lblcustaddress").vw.setWidth((int)((views.get("pnljodetstyle5").vw.getWidth())-(1d / 100 * width) - ((2d / 100 * width))));
views.get("lblcustaddress").vw.setTop((int)((0.25d / 100 * height)));
views.get("lblcustaddress").vw.setHeight((int)((views.get("pnljodetstyle5").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("lblcaption4").vw.setTop((int)((views.get("pnljodetstyle5").vw.getTop() + views.get("pnljodetstyle5").vw.getHeight())+(3d * scale)));
views.get("pnljodetstyle6").vw.setTop((int)((views.get("pnljodetstyle5").vw.getTop() + views.get("pnljodetstyle5").vw.getHeight())+(3d * scale)));
views.get("pnljodetstyle6").vw.setLeft((int)((views.get("lblcaption4").vw.getLeft() + views.get("lblcaption4").vw.getWidth())+(2d * scale)));
views.get("pnljodetstyle6").vw.setWidth((int)((views.get("pnljodetails").vw.getWidth())-(2d / 100 * width) - ((views.get("lblcaption4").vw.getLeft() + views.get("lblcaption4").vw.getWidth())+(2d * scale))));
views.get("lblacctclass").vw.setLeft((int)((2d / 100 * width)));
views.get("lblacctclass").vw.setWidth((int)((views.get("pnljodetstyle6").vw.getWidth())-(1d / 100 * width) - ((2d / 100 * width))));
views.get("lblacctclass").vw.setTop((int)((0.25d / 100 * height)));
views.get("lblacctclass").vw.setHeight((int)((views.get("pnljodetstyle6").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("pnlfindings").vw.setTop((int)((views.get("pnljodetails").vw.getTop() + views.get("pnljodetails").vw.getHeight())+(5d * scale)));
views.get("pnlfindings").vw.setLeft((int)((1d / 100 * width)));
views.get("pnlfindings").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("pnlfindings").vw.setHeight((int)((47d / 100 * height)));
views.get("lblfindingstitle").vw.setLeft((int)((0d / 100 * width)));
views.get("lblfindingstitle").vw.setWidth((int)((views.get("pnlfindings").vw.getWidth()) - ((0d / 100 * width))));
views.get("lblcaption5").vw.setTop((int)((views.get("lblfindingstitle").vw.getTop() + views.get("lblfindingstitle").vw.getHeight())+(5d * scale)));
views.get("lblcaption5").vw.setLeft((int)((2d / 100 * width)));
views.get("pnlbookanchor").vw.setTop((int)((views.get("lblfindingstitle").vw.getTop() + views.get("lblfindingstitle").vw.getHeight())+(5d * scale)));
views.get("pnlbookanchor").vw.setLeft((int)((views.get("lblcaption5").vw.getLeft() + views.get("lblcaption5").vw.getWidth())+(5d * scale)));
views.get("pnlbookanchor").vw.setWidth((int)((views.get("pnlfindings").vw.getWidth())-(2d / 100 * width) - ((views.get("lblcaption5").vw.getLeft() + views.get("lblcaption5").vw.getWidth())+(5d * scale))));
views.get("cbobookno").vw.setLeft((int)((1d / 100 * width)));
views.get("cbobookno").vw.setWidth((int)((views.get("pnlbookanchor").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("cbobookno").vw.setTop((int)((0.5d / 100 * height)));
views.get("cbobookno").vw.setHeight((int)((views.get("pnlbookanchor").vw.getHeight())-(0.5d / 100 * height) - ((0.5d / 100 * height))));
views.get("lblcaption6").vw.setLeft((int)((views.get("lblcaption5").vw.getLeft() + views.get("lblcaption5").vw.getWidth()) - (views.get("lblcaption6").vw.getWidth())));
views.get("lblcaption6").vw.setTop((int)((views.get("lblcaption5").vw.getTop() + views.get("lblcaption5").vw.getHeight())+(5d * scale)));
views.get("pnlseqnoanchor").vw.setTop((int)((views.get("lblcaption6").vw.getTop())));
views.get("pnlseqnoanchor").vw.setLeft((int)((views.get("lblcaption6").vw.getLeft() + views.get("lblcaption6").vw.getWidth())+(5d * scale)));
views.get("pnlseqnoanchor").vw.setWidth((int)((views.get("pnlfindings").vw.getWidth())-(35d / 100 * width) - ((views.get("lblcaption6").vw.getLeft() + views.get("lblcaption6").vw.getWidth())+(5d * scale))));
views.get("txtseqno").vw.setLeft((int)((2d / 100 * width)));
views.get("txtseqno").vw.setWidth((int)((views.get("pnlseqnoanchor").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("txtseqno").vw.setTop((int)((0.25d / 100 * height)));
views.get("txtseqno").vw.setHeight((int)((views.get("pnlseqnoanchor").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("lblcaption7").vw.setLeft((int)((views.get("lblcaption5").vw.getLeft() + views.get("lblcaption5").vw.getWidth()) - (views.get("lblcaption7").vw.getWidth())));
views.get("lblcaption7").vw.setTop((int)((views.get("lblcaption6").vw.getTop() + views.get("lblcaption6").vw.getHeight())+(5d * scale)));
views.get("pnlmeterbrandanchor").vw.setTop((int)((views.get("lblcaption7").vw.getTop())));
views.get("pnlmeterbrandanchor").vw.setLeft((int)((views.get("lblcaption7").vw.getLeft() + views.get("lblcaption7").vw.getWidth())+(5d * scale)));
views.get("pnlmeterbrandanchor").vw.setWidth((int)((views.get("pnlfindings").vw.getWidth())-(35d / 100 * width) - ((views.get("lblcaption7").vw.getLeft() + views.get("lblcaption7").vw.getWidth())+(5d * scale))));
views.get("cbometerbrand").vw.setLeft((int)((1d / 100 * width)));
views.get("cbometerbrand").vw.setWidth((int)((views.get("pnlmeterbrandanchor").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("cbometerbrand").vw.setTop((int)((0.5d / 100 * height)));
views.get("cbometerbrand").vw.setHeight((int)((views.get("pnlmeterbrandanchor").vw.getHeight())-(0.5d / 100 * height) - ((0.5d / 100 * height))));
views.get("lblcaption8").vw.setLeft((int)((views.get("lblcaption7").vw.getLeft() + views.get("lblcaption7").vw.getWidth()) - (views.get("lblcaption8").vw.getWidth())));
views.get("lblcaption8").vw.setTop((int)((views.get("lblcaption7").vw.getTop() + views.get("lblcaption7").vw.getHeight())+(5d * scale)));
views.get("pnlmeternoanchor").vw.setTop((int)((views.get("lblcaption8").vw.getTop())));
views.get("pnlmeternoanchor").vw.setLeft((int)((views.get("lblcaption8").vw.getLeft() + views.get("lblcaption8").vw.getWidth())+(5d * scale)));
views.get("pnlmeternoanchor").vw.setWidth((int)((views.get("pnlfindings").vw.getWidth())-(42d / 100 * width) - ((views.get("lblcaption8").vw.getLeft() + views.get("lblcaption8").vw.getWidth())+(5d * scale))));
views.get("txtmeterno").vw.setLeft((int)((2d / 100 * width)));
views.get("txtmeterno").vw.setWidth((int)((views.get("pnlmeternoanchor").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("txtmeterno").vw.setTop((int)((0.25d / 100 * height)));
views.get("txtmeterno").vw.setHeight((int)((views.get("pnlmeternoanchor").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("lblcaption9").vw.setLeft((int)((views.get("pnlmeternoanchor").vw.getLeft() + views.get("pnlmeternoanchor").vw.getWidth())+(5d * scale)));
views.get("lblcaption9").vw.setTop((int)((views.get("lblcaption8").vw.getTop())));
views.get("pnlinitrdg").vw.setTop((int)((views.get("lblcaption9").vw.getTop())));
views.get("pnlinitrdg").vw.setLeft((int)((views.get("lblcaption9").vw.getLeft() + views.get("lblcaption9").vw.getWidth())+(5d * scale)));
views.get("pnlinitrdg").vw.setWidth((int)((views.get("pnlfindings").vw.getWidth())-(2d / 100 * width) - ((views.get("lblcaption9").vw.getLeft() + views.get("lblcaption9").vw.getWidth())+(5d * scale))));
views.get("txtinitrdg").vw.setLeft((int)((2d / 100 * width)));
views.get("txtinitrdg").vw.setWidth((int)((views.get("pnlinitrdg").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("txtinitrdg").vw.setTop((int)((0.25d / 100 * height)));
views.get("txtinitrdg").vw.setHeight((int)((views.get("pnlinitrdg").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("pnlwaterlossfindings").vw.setTop((int)((views.get("pnlfindings").vw.getTop() + views.get("pnlfindings").vw.getHeight())+(5d * scale)));
views.get("pnlwaterlossfindings").vw.setLeft((int)((1d / 100 * width)));
views.get("pnlwaterlossfindings").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("pnlwaterlossfindings").vw.setHeight((int)((55d / 100 * height)));
views.get("lblwaterlossfindings").vw.setLeft((int)((0d / 100 * width)));
views.get("lblwaterlossfindings").vw.setWidth((int)((views.get("pnlwaterlossfindings").vw.getWidth()) - ((0d / 100 * width))));
views.get("lblpipetype").vw.setTop((int)((views.get("lblwaterlossfindings").vw.getTop() + views.get("lblwaterlossfindings").vw.getHeight())+(5d * scale)));
views.get("lblpipetype").vw.setLeft((int)((2d / 100 * width)));
views.get("pnlpipetypeanchor").vw.setTop((int)((views.get("lblwaterlossfindings").vw.getTop() + views.get("lblwaterlossfindings").vw.getHeight())+(5d * scale)));
views.get("pnlpipetypeanchor").vw.setLeft((int)((views.get("lblpipetype").vw.getLeft() + views.get("lblpipetype").vw.getWidth())+(5d * scale)));
views.get("pnlpipetypeanchor").vw.setWidth((int)((views.get("pnlwaterlossfindings").vw.getWidth())-(2d / 100 * width) - ((views.get("lblpipetype").vw.getLeft() + views.get("lblpipetype").vw.getWidth())+(5d * scale))));
views.get("cbopipetype").vw.setLeft((int)((1.75d / 100 * width)));
views.get("cbopipetype").vw.setWidth((int)((views.get("pnlpipetypeanchor").vw.getWidth())-(1.75d / 100 * width) - ((1.75d / 100 * width))));
views.get("cbopipetype").vw.setTop((int)((0.5d / 100 * height)));
views.get("cbopipetype").vw.setHeight((int)((views.get("pnlpipetypeanchor").vw.getHeight())-(0.5d / 100 * height) - ((0.5d / 100 * height))));
views.get("lblpipesize").vw.setLeft((int)((views.get("lblpipetype").vw.getLeft() + views.get("lblpipetype").vw.getWidth()) - (views.get("lblpipesize").vw.getWidth())));
views.get("lblpipesize").vw.setTop((int)((views.get("lblpipetype").vw.getTop() + views.get("lblpipetype").vw.getHeight())+(5d * scale)));
views.get("pnlpipesizeanchor").vw.setTop((int)((views.get("lblpipesize").vw.getTop())));
views.get("pnlpipesizeanchor").vw.setLeft((int)((views.get("lblpipesize").vw.getLeft() + views.get("lblpipesize").vw.getWidth())+(5d * scale)));
views.get("pnlpipesizeanchor").vw.setWidth((int)((views.get("pnlwaterlossfindings").vw.getWidth())-(2d / 100 * width) - ((views.get("lblpipesize").vw.getLeft() + views.get("lblpipesize").vw.getWidth())+(5d * scale))));
views.get("cbopipesize").vw.setLeft((int)((1d / 100 * width)));
views.get("cbopipesize").vw.setWidth((int)((views.get("pnlpipesizeanchor").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("cbopipesize").vw.setTop((int)((0.5d / 100 * height)));
views.get("cbopipesize").vw.setHeight((int)((views.get("pnlpipesizeanchor").vw.getHeight())-(0.5d / 100 * height) - ((0.5d / 100 * height))));
views.get("lblpressure").vw.setLeft((int)((views.get("lblpipesize").vw.getLeft() + views.get("lblpipesize").vw.getWidth()) - (views.get("lblpressure").vw.getWidth())));
views.get("lblpressure").vw.setTop((int)((views.get("lblpipesize").vw.getTop() + views.get("lblpipesize").vw.getHeight())+(5d * scale)));
views.get("pnlpsianchor").vw.setTop((int)((views.get("lblpressure").vw.getTop())));
views.get("pnlpsianchor").vw.setLeft((int)((views.get("lblpressure").vw.getLeft() + views.get("lblpressure").vw.getWidth())+(5d * scale)));
views.get("pnlpsianchor").vw.setWidth((int)((views.get("pnlwaterlossfindings").vw.getWidth())-(40d / 100 * width) - ((views.get("lblpressure").vw.getLeft() + views.get("lblpressure").vw.getWidth())+(5d * scale))));
views.get("txtpsi").vw.setLeft((int)((1.75d / 100 * width)));
views.get("txtpsi").vw.setWidth((int)((views.get("pnlpsianchor").vw.getWidth())-(1.75d / 100 * width) - ((1.75d / 100 * width))));
views.get("txtpsi").vw.setTop((int)((0.25d / 100 * height)));
views.get("txtpsi").vw.setHeight((int)((views.get("pnlpsianchor").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("lblminutes").vw.setLeft((int)((3d / 100 * width)));
views.get("lblminutes").vw.setTop((int)((views.get("lblpressure").vw.getTop() + views.get("lblpressure").vw.getHeight())+(5d * scale)));
views.get("pnlminutes").vw.setTop((int)((views.get("lblminutes").vw.getTop())));
views.get("pnlminutes").vw.setLeft((int)((views.get("lblminutes").vw.getLeft() + views.get("lblminutes").vw.getWidth())+(5d * scale)));
views.get("pnlminutes").vw.setWidth((int)((views.get("pnlwaterlossfindings").vw.getWidth())-(13d / 100 * width) - ((views.get("lblminutes").vw.getLeft() + views.get("lblminutes").vw.getWidth())+(5d * scale))));
views.get("txtminutes").vw.setLeft((int)((2d / 100 * width)));
views.get("txtminutes").vw.setWidth((int)((views.get("pnlminutes").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("txtminutes").vw.setTop((int)((0.25d / 100 * height)));
views.get("txtminutes").vw.setHeight((int)((views.get("pnlminutes").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("lblmins").vw.setLeft((int)((views.get("pnlminutes").vw.getLeft() + views.get("pnlminutes").vw.getWidth())+(2d * scale)));
views.get("lblmins").vw.setTop((int)((views.get("lblminutes").vw.getTop() + views.get("lblminutes").vw.getHeight()/2) - (views.get("lblmins").vw.getHeight() / 2)));
views.get("lblwl").vw.setLeft((int)((views.get("lblminutes").vw.getLeft() + views.get("lblminutes").vw.getWidth()) - (views.get("lblwl").vw.getWidth())));
views.get("lblwl").vw.setTop((int)((views.get("lblminutes").vw.getTop() + views.get("lblminutes").vw.getHeight())+(5d * scale)));
views.get("pnlwaterlossanchor").vw.setTop((int)((views.get("lblwl").vw.getTop())));
views.get("pnlwaterlossanchor").vw.setLeft((int)((views.get("lblwl").vw.getLeft() + views.get("lblwl").vw.getWidth())+(5d * scale)));
views.get("pnlwaterlossanchor").vw.setWidth((int)((views.get("pnlwaterlossfindings").vw.getWidth())-(13d / 100 * width) - ((views.get("lblwl").vw.getLeft() + views.get("lblwl").vw.getWidth())+(5d * scale))));
views.get("txtwaterloss").vw.setLeft((int)((2d / 100 * width)));
views.get("txtwaterloss").vw.setWidth((int)((views.get("pnlwaterlossanchor").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("txtwaterloss").vw.setTop((int)((0.25d / 100 * height)));
views.get("txtwaterloss").vw.setHeight((int)((views.get("pnlwaterlossanchor").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("lblcum").vw.setLeft((int)((views.get("pnlwaterlossanchor").vw.getLeft() + views.get("pnlwaterlossanchor").vw.getWidth())+(2d * scale)));
views.get("lblcum").vw.setTop((int)((views.get("lblwl").vw.getTop())));
views.get("pnlremarks").vw.setTop((int)((views.get("pnlwaterlossfindings").vw.getTop() + views.get("pnlwaterlossfindings").vw.getHeight())+(5d * scale)));
views.get("pnlremarks").vw.setLeft((int)((1d / 100 * width)));
views.get("pnlremarks").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("pnlremarks").vw.setHeight((int)((21d / 100 * height)));
views.get("lblremarkstitle").vw.setLeft((int)((0d / 100 * width)));
views.get("lblremarkstitle").vw.setWidth((int)((views.get("pnlremarks").vw.getWidth()) - ((0d / 100 * width))));
views.get("lblremarkstitle").vw.setTop((int)((0d / 100 * height)));
views.get("pnlremarksanchor").vw.setLeft((int)((1d / 100 * width)));
views.get("pnlremarksanchor").vw.setWidth((int)((views.get("pnlremarks").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("pnlremarksanchor").vw.setTop((int)((views.get("lblremarkstitle").vw.getTop() + views.get("lblremarkstitle").vw.getHeight())+(5d * scale)));
views.get("pnlremarksanchor").vw.setHeight((int)((views.get("pnlremarks").vw.getHeight())-(1d / 100 * height) - ((views.get("lblremarkstitle").vw.getTop() + views.get("lblremarkstitle").vw.getHeight())+(5d * scale))));
views.get("txtremarks").vw.setLeft((int)((2d / 100 * width)));
views.get("txtremarks").vw.setWidth((int)((views.get("pnlremarksanchor").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("txtremarks").vw.setTop((int)((1d / 100 * height)));
views.get("txtremarks").vw.setHeight((int)((views.get("pnlremarksanchor").vw.getHeight())-(1d / 100 * height) - ((1d / 100 * height))));
views.get("btnsaveupdate").vw.setTop((int)((views.get("pnlremarks").vw.getTop() + views.get("pnlremarks").vw.getHeight())+(10d * scale)));
views.get("btnsaveupdate").vw.setHeight((int)((views.get("pnlmain").vw.getHeight())-(2d / 100 * height) - ((views.get("pnlremarks").vw.getTop() + views.get("pnlremarks").vw.getHeight())+(10d * scale))));
views.get("btnsaveupdate").vw.setLeft((int)((2d / 100 * width)));
views.get("btnsaveupdate").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("pnlsignature").vw.setLeft((int)((0d / 100 * width)));
views.get("pnlsignature").vw.setWidth((int)((100d / 100 * width) - ((0d / 100 * width))));
views.get("pnlsignature").vw.setTop((int)(0-(10d / 100 * height)));
views.get("pnlsignature").vw.setHeight((int)((130d / 100 * height)));
views.get("pnlmainsigbg").vw.setLeft((int)((2d / 100 * width)));
views.get("pnlmainsigbg").vw.setWidth((int)((views.get("pnlsignature").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("pnlmainsigbg").vw.setTop((int)((20d / 100 * height)));
views.get("pnlmainsigbg").vw.setHeight((int)((views.get("pnlsignature").vw.getHeight())-(50d / 100 * height) - ((20d / 100 * height))));
views.get("lblcustsignature").vw.setLeft((int)((0d / 100 * width)));
views.get("lblcustsignature").vw.setWidth((int)((views.get("pnlmainsigbg").vw.getWidth()) - ((0d / 100 * width))));
views.get("lblcustsignature").vw.setTop((int)((0d / 100 * height)));
views.get("pnlsigbg").vw.setLeft((int)((3d / 100 * width)));
views.get("pnlsigbg").vw.setWidth((int)((views.get("pnlmainsigbg").vw.getWidth())-(3d / 100 * width) - ((3d / 100 * width))));
views.get("pnlsigbg").vw.setTop((int)((views.get("lblcustsignature").vw.getTop() + views.get("lblcustsignature").vw.getHeight())+(5d * scale)));
views.get("pnlsigbg").vw.setHeight((int)((views.get("pnlmainsigbg").vw.getHeight())-(15d / 100 * height) - ((views.get("lblcustsignature").vw.getTop() + views.get("lblcustsignature").vw.getHeight())+(5d * scale))));
views.get("btnconfirmsig").vw.setLeft((int)((views.get("pnlsigbg").vw.getLeft())));
views.get("btnconfirmsig").vw.setWidth((int)((views.get("pnlsigbg").vw.getLeft() + views.get("pnlsigbg").vw.getWidth()) - ((views.get("pnlsigbg").vw.getLeft()))));
views.get("btnconfirmsig").vw.setTop((int)((views.get("pnlsigbg").vw.getTop() + views.get("pnlsigbg").vw.getHeight())+(10d * scale)));
views.get("btnconfirmsig").vw.setHeight((int)((views.get("pnlmainsigbg").vw.getHeight())-(2d / 100 * height) - ((views.get("pnlsigbg").vw.getTop() + views.get("pnlsigbg").vw.getHeight())+(10d * scale))));
views.get("signaturepad").vw.setLeft((int)((1.5d / 100 * width)));
views.get("signaturepad").vw.setWidth((int)((views.get("pnlsigbg").vw.getWidth())-(1.5d / 100 * width) - ((1.5d / 100 * width))));
views.get("signaturepad").vw.setTop((int)((1.5d / 100 * height)));
views.get("signaturepad").vw.setHeight((int)((views.get("pnlsigbg").vw.getHeight())-(1.5d / 100 * height) - ((1.5d / 100 * height))));
views.get("pnlconfirmsig").vw.setLeft((int)((0d / 100 * width)));
views.get("pnlconfirmsig").vw.setWidth((int)((100d / 100 * width) - ((0d / 100 * width))));
views.get("pnlconfirmsig").vw.setTop((int)((0d / 100 * height)));
views.get("pnlconfirmsig").vw.setHeight((int)((120d / 100 * height) - ((0d / 100 * height))));
views.get("pnlmainsigbg2").vw.setLeft((int)((1d / 100 * width)));
views.get("pnlmainsigbg2").vw.setWidth((int)((views.get("pnlconfirmsig").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("pnlmainsigbg2").vw.setTop((int)((10d / 100 * height)));
views.get("pnlmainsigbg2").vw.setHeight((int)((views.get("pnlconfirmsig").vw.getHeight())-(15d / 100 * height) - ((10d / 100 * height))));
views.get("lblconfirmsig").vw.setLeft((int)((0d / 100 * width)));
views.get("lblconfirmsig").vw.setWidth((int)((views.get("pnlmainsigbg2").vw.getWidth()) - ((0d / 100 * width))));
views.get("lblconfirmsig").vw.setTop((int)((0d / 100 * height)));
views.get("pnlimagesig").vw.setLeft((int)((3d / 100 * width)));
views.get("pnlimagesig").vw.setWidth((int)((views.get("pnlmainsigbg2").vw.getWidth())-(3d / 100 * width) - ((3d / 100 * width))));
views.get("pnlimagesig").vw.setTop((int)((views.get("lblconfirmsig").vw.getTop() + views.get("lblconfirmsig").vw.getHeight())+(5d * scale)));
views.get("pnlimagesig").vw.setHeight((int)((views.get("pnlmainsigbg2").vw.getHeight())-(50d / 100 * height) - ((views.get("lblconfirmsig").vw.getTop() + views.get("lblconfirmsig").vw.getHeight())+(5d * scale))));
views.get("imgsignature").vw.setLeft((int)((2d / 100 * width)));
views.get("imgsignature").vw.setWidth((int)((views.get("pnlimagesig").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("imgsignature").vw.setTop((int)((2d / 100 * height)));
views.get("imgsignature").vw.setHeight((int)((views.get("pnlimagesig").vw.getHeight())-(2d / 100 * height) - ((2d / 100 * height))));
views.get("lblaccomplishedby").vw.setLeft((int)((2d / 100 * width)));
views.get("lblaccomplishedby").vw.setWidth((int)((views.get("pnlmainsigbg2").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("lblaccomplishedby").vw.setTop((int)((views.get("pnlimagesig").vw.getTop() + views.get("pnlimagesig").vw.getHeight())+(10d * scale)));
views.get("pnlplumberanchor").vw.setLeft((int)((2d / 100 * width)));
views.get("pnlplumberanchor").vw.setWidth((int)((views.get("pnlmainsigbg2").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("pnlplumberanchor").vw.setTop((int)((views.get("lblaccomplishedby").vw.getTop() + views.get("lblaccomplishedby").vw.getHeight())+(2d * scale)));
views.get("spnplumbers").vw.setLeft((int)((1d / 100 * width)));
views.get("spnplumbers").vw.setWidth((int)((views.get("pnlplumberanchor").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("spnplumbers").vw.setTop((int)((1d / 100 * height)));
views.get("spnplumbers").vw.setHeight((int)((views.get("pnlplumberanchor").vw.getHeight())-(1d / 100 * height) - ((1d / 100 * height))));
views.get("lbldatetimestart").vw.setTop((int)((views.get("pnlplumberanchor").vw.getTop() + views.get("pnlplumberanchor").vw.getHeight())+(5d * scale)));
views.get("lbldatetimestart").vw.setLeft((int)((2d / 100 * width)));
views.get("pnlstartedanchor").vw.setTop((int)((views.get("lbldatetimestart").vw.getTop())));
views.get("pnlstartedanchor").vw.setLeft((int)((views.get("lbldatetimestart").vw.getLeft() + views.get("lbldatetimestart").vw.getWidth())+(5d * scale)));
views.get("pnlstartedanchor").vw.setWidth((int)((views.get("pnlmainsigbg2").vw.getWidth())-(2d / 100 * width) - ((views.get("lbldatetimestart").vw.getLeft() + views.get("lbldatetimestart").vw.getWidth())+(5d * scale))));
views.get("txtdatetimestarted").vw.setLeft((int)((1d / 100 * width)));
views.get("txtdatetimestarted").vw.setWidth((int)((views.get("pnlstartedanchor").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("txtdatetimestarted").vw.setTop((int)((0.75d / 100 * height)));
views.get("txtdatetimestarted").vw.setHeight((int)((views.get("pnlstartedanchor").vw.getHeight())-(0.75d / 100 * height) - ((0.75d / 100 * height))));
views.get("lbldatetimefinished").vw.setTop((int)((views.get("lbldatetimestart").vw.getTop() + views.get("lbldatetimestart").vw.getHeight())+(5d * scale)));
views.get("lbldatetimefinished").vw.setLeft((int)((2d / 100 * width)));
views.get("pnlfinishedanchor").vw.setTop((int)((views.get("lbldatetimefinished").vw.getTop())));
views.get("pnlfinishedanchor").vw.setLeft((int)((views.get("lbldatetimestart").vw.getLeft() + views.get("lbldatetimestart").vw.getWidth())+(5d * scale)));
views.get("pnlfinishedanchor").vw.setWidth((int)((views.get("pnlmainsigbg2").vw.getWidth())-(2d / 100 * width) - ((views.get("lbldatetimestart").vw.getLeft() + views.get("lbldatetimestart").vw.getWidth())+(5d * scale))));
views.get("txtdatetimefinished").vw.setLeft((int)((1d / 100 * width)));
views.get("txtdatetimefinished").vw.setWidth((int)((views.get("pnlfinishedanchor").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("txtdatetimefinished").vw.setTop((int)((0.75d / 100 * height)));
views.get("txtdatetimefinished").vw.setHeight((int)((views.get("pnlfinishedanchor").vw.getHeight())-(0.75d / 100 * height) - ((0.75d / 100 * height))));
views.get("btncancel").vw.setLeft((int)((3d / 100 * width)));
views.get("btncancel").vw.setWidth((int)((views.get("pnlmainsigbg2").vw.getWidth())-(65d / 100 * width) - ((3d / 100 * width))));
views.get("btncancel").vw.setTop((int)((views.get("pnlfinishedanchor").vw.getTop() + views.get("pnlfinishedanchor").vw.getHeight())+(10d * scale)));
views.get("btnclear").vw.setLeft((int)((36d / 100 * width)));
views.get("btnclear").vw.setWidth((int)((views.get("pnlmainsigbg2").vw.getWidth())-(32d / 100 * width) - ((36d / 100 * width))));
views.get("btnclear").vw.setTop((int)((views.get("pnlfinishedanchor").vw.getTop() + views.get("pnlfinishedanchor").vw.getHeight())+(10d * scale)));
views.get("btnok").vw.setLeft((int)((69d / 100 * width)));
views.get("btnok").vw.setWidth((int)((views.get("pnlmainsigbg2").vw.getWidth())-(2d / 100 * width) - ((69d / 100 * width))));
views.get("btnok").vw.setTop((int)((views.get("pnlfinishedanchor").vw.getTop() + views.get("pnlfinishedanchor").vw.getHeight())+(10d * scale)));

}
}