package bwsi.PumpOperations.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_newgpmcalc{

public static void LS_general(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
anywheresoftware.b4a.keywords.LayoutBuilder.scaleAll(views);
views.get("toolbar").vw.setTop((int)((0d * scale)));
if ((anywheresoftware.b4a.keywords.LayoutBuilder.getScreenSize()>6.5d)) { 
;
views.get("toolbar").vw.setHeight((int)((64d * scale)));
;}else{ 
;
if ((BA.ObjectToBoolean( String.valueOf(anywheresoftware.b4a.keywords.LayoutBuilder.isPortrait())))) { 
;
views.get("toolbar").vw.setHeight((int)((50d * scale)));
;}else{ 
;
views.get("toolbar").vw.setHeight((int)((42d * scale)));
;};
;};
views.get("pnlmain").vw.setLeft((int)(0d));
views.get("pnlmain").vw.setWidth((int)((100d / 100 * width)));
views.get("pnlmain").vw.setTop((int)((views.get("toolbar").vw.getTop() + views.get("toolbar").vw.getHeight())));
views.get("pnlmain").vw.setHeight((int)((100d / 100 * height) - ((views.get("toolbar").vw.getTop() + views.get("toolbar").vw.getHeight()))));
views.get("pnlgpm").vw.setTop((int)((1d / 100 * height)));
views.get("pnlgpm").vw.setHeight((int)((views.get("pnlmain").vw.getHeight())-(82d / 100 * height) - ((1d / 100 * height))));
views.get("pnlgpm").vw.setLeft((int)((1d / 100 * width)));
views.get("pnlgpm").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(2d / 100 * width) - ((1d / 100 * width))));
views.get("txtgpm").vw.setTop((int)((0.25d / 100 * height)));
views.get("txtgpm").vw.setHeight((int)((views.get("pnlgpm").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("txtgpm").vw.setLeft((int)((1d / 100 * width)));
views.get("txtgpm").vw.setWidth((int)((views.get("pnlgpm").vw.getWidth())-(3d / 100 * width) - ((1d / 100 * width))));
views.get("pnlinputs").vw.setLeft((int)((1d / 100 * width)));
views.get("pnlinputs").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("pnlinputs").vw.setTop((int)((views.get("pnlgpm").vw.getTop() + views.get("pnlgpm").vw.getHeight())+(10d * scale)));
views.get("pnlinputs").vw.setHeight((int)((views.get("pnlmain").vw.getHeight())-(69d / 100 * height) - ((views.get("pnlgpm").vw.getTop() + views.get("pnlgpm").vw.getHeight())+(10d * scale))));
views.get("lblinputtitle").vw.setTop((int)(0d));
views.get("lblinputtitle").vw.setLeft((int)(0d));
views.get("lblinputtitle").vw.setWidth((int)((views.get("pnlinputs").vw.getWidth()) - (0d)));
views.get("lbl1").vw.setLeft((int)((2.5d / 100 * width)));
views.get("lbl1").vw.setTop((int)((views.get("lblinputtitle").vw.getTop() + views.get("lblinputtitle").vw.getHeight())+(5d * scale)));
views.get("pnlbucketsize").vw.setLeft((int)((views.get("lbl1").vw.getLeft() + views.get("lbl1").vw.getWidth())+(5d * scale)));
views.get("pnlbucketsize").vw.setWidth((int)((views.get("pnlinputs").vw.getWidth())-(57d / 100 * width) - ((views.get("lbl1").vw.getLeft() + views.get("lbl1").vw.getWidth())+(5d * scale))));
views.get("pnlbucketsize").vw.setTop((int)((views.get("lblinputtitle").vw.getTop() + views.get("lblinputtitle").vw.getHeight())+(5d * scale)));
views.get("txtbucketsize").vw.setLeft((int)((1d / 100 * width)));
views.get("txtbucketsize").vw.setWidth((int)((views.get("pnlbucketsize").vw.getWidth())-(2d / 100 * width) - ((1d / 100 * width))));
views.get("txtbucketsize").vw.setTop((int)((0.5d / 100 * height)));
views.get("txtbucketsize").vw.setHeight((int)((views.get("pnlbucketsize").vw.getHeight())-(0.5d / 100 * height) - ((0.5d / 100 * height))));
views.get("lbl2").vw.setLeft((int)((views.get("pnlbucketsize").vw.getLeft() + views.get("pnlbucketsize").vw.getWidth())+(10d * scale)));
views.get("lbl2").vw.setTop((int)((views.get("lblinputtitle").vw.getTop() + views.get("lblinputtitle").vw.getHeight())+(5d * scale)));
views.get("pnluom").vw.setLeft((int)((views.get("lbl2").vw.getLeft() + views.get("lbl2").vw.getWidth())+(5d * scale)));
views.get("pnluom").vw.setWidth((int)((views.get("pnlinputs").vw.getWidth())-(2d / 100 * width) - ((views.get("lbl2").vw.getLeft() + views.get("lbl2").vw.getWidth())+(5d * scale))));
views.get("pnluom").vw.setTop((int)((views.get("lblinputtitle").vw.getTop() + views.get("lblinputtitle").vw.getHeight())+(5d * scale)));
views.get("cbouom").vw.setLeft((int)((2d / 100 * width)));
views.get("cbouom").vw.setWidth((int)((views.get("pnluom").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("cbouom").vw.setTop((int)((0.5d / 100 * height)));
views.get("cbouom").vw.setHeight((int)((views.get("pnluom").vw.getHeight())-(0.5d / 100 * height) - ((0.5d / 100 * height))));
views.get("pnltry").vw.setLeft((int)((1d / 100 * width)));
views.get("pnltry").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("pnltry").vw.setTop((int)((views.get("pnlinputs").vw.getTop() + views.get("pnlinputs").vw.getHeight())+(10d * scale)));
views.get("pnltry").vw.setHeight((int)((views.get("pnlmain").vw.getHeight())-(37d / 100 * height) - ((views.get("pnlinputs").vw.getTop() + views.get("pnlinputs").vw.getHeight())+(10d * scale))));
views.get("lbltrytitle").vw.setLeft((int)((0d / 100 * width)));
views.get("lbltrytitle").vw.setWidth((int)((views.get("pnltry").vw.getWidth()) - ((0d / 100 * width))));
views.get("lbltrytitle").vw.setTop((int)((0d / 100 * height)));
views.get("chkmanual").vw.setTop((int)((views.get("lbltrytitle").vw.getTop() + views.get("lbltrytitle").vw.getHeight())+(5d * scale)));
views.get("chkmanual").vw.setLeft((int)((10d * scale)));
views.get("chkmanual").vw.setWidth((int)((views.get("pnltry").vw.getWidth())-(10d * scale) - ((10d * scale))));
views.get("label1").vw.setTop((int)((views.get("chkmanual").vw.getTop() + views.get("chkmanual").vw.getHeight())+(5d * scale)));
views.get("pnl1st").vw.setTop((int)((views.get("chkmanual").vw.getTop() + views.get("chkmanual").vw.getHeight())+(5d * scale)));
views.get("pnl1st").vw.setLeft((int)((views.get("label1").vw.getLeft() + views.get("label1").vw.getWidth())));
views.get("pnl1st").vw.setWidth((int)((views.get("pnltry").vw.getWidth())-(45d / 100 * width) - ((views.get("label1").vw.getLeft() + views.get("label1").vw.getWidth()))));
views.get("txttry1").vw.setLeft((int)((1d / 100 * width)));
views.get("txttry1").vw.setWidth((int)((views.get("pnl1st").vw.getWidth())-(3d / 100 * width) - ((1d / 100 * width))));
views.get("txttry1").vw.setTop((int)((0.5d / 100 * height)));
views.get("txttry1").vw.setHeight((int)((views.get("pnl1st").vw.getHeight())-(0.5d / 100 * height) - ((0.5d / 100 * height))));
views.get("pnlcover1").vw.setLeft((int)((views.get("pnltry").vw.getWidth())-(47d / 100 * width)));
views.get("pnlcover1").vw.setTop((int)((views.get("pnl1st").vw.getTop())));
views.get("pnlcover1").vw.setHeight((int)((views.get("pnl1st").vw.getTop() + views.get("pnl1st").vw.getHeight()) - ((views.get("pnl1st").vw.getTop()))));
views.get("pnlstyle1").vw.setLeft((int)((views.get("pnlcover1").vw.getLeft() + views.get("pnlcover1").vw.getWidth())-(7.5d * scale)));
views.get("pnlstyle1").vw.setWidth((int)((views.get("pnltry").vw.getWidth())-(34d / 100 * width) - ((views.get("pnlcover1").vw.getLeft() + views.get("pnlcover1").vw.getWidth())-(7.5d * scale))));
views.get("pnlstyle1").vw.setTop((int)((views.get("pnl1st").vw.getTop())));
views.get("pnlstyle1").vw.setHeight((int)((views.get("pnl1st").vw.getTop() + views.get("pnl1st").vw.getHeight()) - ((views.get("pnl1st").vw.getTop()))));
views.get("lblsec1").vw.setHeight((int)((views.get("pnlstyle1").vw.getHeight())));
views.get("lblsec1").vw.setWidth((int)((views.get("pnlstyle1").vw.getWidth())));
views.get("btnshowtimer1").vw.setLeft((int)((views.get("pnlstyle1").vw.getLeft() + views.get("pnlstyle1").vw.getWidth())+(3d * scale)));
views.get("btnshowtimer1").vw.setWidth((int)((views.get("pnltry").vw.getWidth())-(3d / 100 * width) - ((views.get("pnlstyle1").vw.getLeft() + views.get("pnlstyle1").vw.getWidth())+(3d * scale))));
views.get("btnshowtimer1").vw.setTop((int)((views.get("label1").vw.getTop())));
views.get("btnshowtimer1").vw.setHeight((int)((views.get("label1").vw.getTop() + views.get("label1").vw.getHeight()) - ((views.get("label1").vw.getTop()))));
views.get("label2").vw.setTop((int)((views.get("label1").vw.getTop() + views.get("label1").vw.getHeight())+(5d * scale)));
views.get("pnl2nd").vw.setTop((int)((views.get("label1").vw.getTop() + views.get("label1").vw.getHeight())+(5d * scale)));
views.get("pnl2nd").vw.setLeft((int)((views.get("label2").vw.getLeft() + views.get("label2").vw.getWidth())));
views.get("pnl2nd").vw.setWidth((int)((views.get("pnltry").vw.getWidth())-(45d / 100 * width) - ((views.get("label2").vw.getLeft() + views.get("label2").vw.getWidth()))));
views.get("txttry2").vw.setLeft((int)((1d / 100 * width)));
views.get("txttry2").vw.setWidth((int)((views.get("pnl2nd").vw.getWidth())-(3d / 100 * width) - ((1d / 100 * width))));
views.get("txttry2").vw.setTop((int)((0.5d / 100 * height)));
views.get("txttry2").vw.setHeight((int)((views.get("pnl2nd").vw.getHeight())-(0.5d / 100 * height) - ((0.5d / 100 * height))));
views.get("pnlcover2").vw.setLeft((int)((views.get("pnltry").vw.getWidth())-(47d / 100 * width)));
views.get("pnlcover2").vw.setTop((int)((views.get("pnl2nd").vw.getTop())));
views.get("pnlcover2").vw.setHeight((int)((views.get("pnl2nd").vw.getTop() + views.get("pnl2nd").vw.getHeight()) - ((views.get("pnl2nd").vw.getTop()))));
views.get("pnlstyle2").vw.setLeft((int)((views.get("pnlcover2").vw.getLeft() + views.get("pnlcover2").vw.getWidth())-(7.5d * scale)));
views.get("pnlstyle2").vw.setWidth((int)((views.get("pnltry").vw.getWidth())-(34d / 100 * width) - ((views.get("pnlcover2").vw.getLeft() + views.get("pnlcover2").vw.getWidth())-(7.5d * scale))));
views.get("pnlstyle2").vw.setTop((int)((views.get("pnl2nd").vw.getTop())));
views.get("pnlstyle2").vw.setHeight((int)((views.get("pnl2nd").vw.getTop() + views.get("pnl2nd").vw.getHeight()) - ((views.get("pnl2nd").vw.getTop()))));
views.get("lblsec2").vw.setHeight((int)((views.get("pnlstyle2").vw.getHeight())));
views.get("lblsec2").vw.setWidth((int)((views.get("pnlstyle2").vw.getWidth())));
views.get("btnshowtimer2").vw.setLeft((int)((views.get("pnlstyle2").vw.getLeft() + views.get("pnlstyle2").vw.getWidth())+(3d * scale)));
views.get("btnshowtimer2").vw.setWidth((int)((views.get("pnltry").vw.getWidth())-(3d / 100 * width) - ((views.get("pnlstyle2").vw.getLeft() + views.get("pnlstyle2").vw.getWidth())+(3d * scale))));
views.get("btnshowtimer2").vw.setTop((int)((views.get("label2").vw.getTop())));
views.get("btnshowtimer2").vw.setHeight((int)((views.get("label2").vw.getTop() + views.get("label2").vw.getHeight()) - ((views.get("label2").vw.getTop()))));
views.get("label3").vw.setTop((int)((views.get("label2").vw.getTop() + views.get("label2").vw.getHeight())+(5d * scale)));
views.get("pnl3rd").vw.setTop((int)((views.get("label2").vw.getTop() + views.get("label2").vw.getHeight())+(5d * scale)));
views.get("pnl3rd").vw.setLeft((int)((views.get("label3").vw.getLeft() + views.get("label3").vw.getWidth())));
views.get("pnl3rd").vw.setWidth((int)((views.get("pnltry").vw.getWidth())-(45d / 100 * width) - ((views.get("label3").vw.getLeft() + views.get("label3").vw.getWidth()))));
views.get("txttry3").vw.setLeft((int)((1d / 100 * width)));
views.get("txttry3").vw.setWidth((int)((views.get("pnl3rd").vw.getWidth())-(3d / 100 * width) - ((1d / 100 * width))));
views.get("txttry3").vw.setTop((int)((0.5d / 100 * height)));
views.get("txttry3").vw.setHeight((int)((views.get("pnl3rd").vw.getHeight())-(0.5d / 100 * height) - ((0.5d / 100 * height))));
views.get("pnlcover3").vw.setLeft((int)((views.get("pnltry").vw.getWidth())-(47d / 100 * width)));
views.get("pnlcover3").vw.setTop((int)((views.get("pnl3rd").vw.getTop())));
views.get("pnlcover3").vw.setHeight((int)((views.get("pnl3rd").vw.getTop() + views.get("pnl3rd").vw.getHeight()) - ((views.get("pnl3rd").vw.getTop()))));
views.get("pnlstyle3").vw.setLeft((int)((views.get("pnlcover2").vw.getLeft() + views.get("pnlcover2").vw.getWidth())-(7.5d * scale)));
views.get("pnlstyle3").vw.setWidth((int)((views.get("pnltry").vw.getWidth())-(34d / 100 * width) - ((views.get("pnlcover2").vw.getLeft() + views.get("pnlcover2").vw.getWidth())-(7.5d * scale))));
views.get("pnlstyle3").vw.setTop((int)((views.get("pnl3rd").vw.getTop())));
views.get("pnlstyle3").vw.setHeight((int)((views.get("pnl3rd").vw.getTop() + views.get("pnl3rd").vw.getHeight()) - ((views.get("pnl3rd").vw.getTop()))));
views.get("lblsec3").vw.setHeight((int)((views.get("pnlstyle3").vw.getHeight())));
views.get("lblsec3").vw.setWidth((int)((views.get("pnlstyle3").vw.getWidth())));
views.get("btnshowtimer3").vw.setLeft((int)((views.get("pnlstyle3").vw.getLeft() + views.get("pnlstyle3").vw.getWidth())+(3d * scale)));
views.get("btnshowtimer3").vw.setWidth((int)((views.get("pnltry").vw.getWidth())-(3d / 100 * width) - ((views.get("pnlstyle3").vw.getLeft() + views.get("pnlstyle3").vw.getWidth())+(3d * scale))));
views.get("btnshowtimer3").vw.setTop((int)((views.get("label3").vw.getTop())));
views.get("btnshowtimer3").vw.setHeight((int)((views.get("label3").vw.getTop() + views.get("label3").vw.getHeight()) - ((views.get("label3").vw.getTop()))));
views.get("pnlwaterquality").vw.setLeft((int)((1d / 100 * width)));
views.get("pnlwaterquality").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("pnlwaterquality").vw.setTop((int)((views.get("pnltry").vw.getTop() + views.get("pnltry").vw.getHeight())+(10d * scale)));
views.get("pnlwaterquality").vw.setHeight((int)((views.get("pnlmain").vw.getHeight())-(24d / 100 * height) - ((views.get("pnltry").vw.getTop() + views.get("pnltry").vw.getHeight())+(10d * scale))));
views.get("lblwaterqualitytitle").vw.setLeft((int)((0d / 100 * width)));
views.get("lblwaterqualitytitle").vw.setWidth((int)((views.get("pnlwaterquality").vw.getWidth()) - ((0d / 100 * width))));
views.get("lblwaterqualitytitle").vw.setTop((int)(0d));
views.get("pnlwaterqualityanchor").vw.setTop((int)((views.get("lblwaterqualitytitle").vw.getTop() + views.get("lblwaterqualitytitle").vw.getHeight())+(5d * scale)));
views.get("pnlwaterqualityanchor").vw.setHeight((int)((views.get("pnlwaterquality").vw.getHeight())-(1d / 100 * height) - ((views.get("lblwaterqualitytitle").vw.getTop() + views.get("lblwaterqualitytitle").vw.getHeight())+(5d * scale))));
views.get("pnlwaterqualityanchor").vw.setLeft((int)((1d / 100 * width)));
views.get("pnlwaterqualityanchor").vw.setWidth((int)((views.get("pnlwaterquality").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("txtwaterquality").vw.setTop((int)((1d / 100 * height)));
views.get("txtwaterquality").vw.setHeight((int)((views.get("pnlwaterqualityanchor").vw.getHeight())-(1d / 100 * height) - ((1d / 100 * height))));
views.get("txtwaterquality").vw.setLeft((int)((1d / 100 * width)));
views.get("txtwaterquality").vw.setWidth((int)((views.get("pnlwaterqualityanchor").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("pnlremarks").vw.setLeft((int)((1d / 100 * width)));
views.get("pnlremarks").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("pnlremarks").vw.setTop((int)((views.get("pnlwaterquality").vw.getTop() + views.get("pnlwaterquality").vw.getHeight())+(10d * scale)));
views.get("pnlremarks").vw.setHeight((int)((views.get("pnlmain").vw.getHeight())-(10d / 100 * height) - ((views.get("pnlwaterquality").vw.getTop() + views.get("pnlwaterquality").vw.getHeight())+(10d * scale))));
views.get("lblremarkstitle").vw.setLeft((int)((0d / 100 * width)));
views.get("lblremarkstitle").vw.setWidth((int)((views.get("pnlremarks").vw.getWidth()) - ((0d / 100 * width))));
views.get("lblremarkstitle").vw.setTop((int)(0d));
views.get("pnlremarksanchor").vw.setTop((int)((views.get("lblremarkstitle").vw.getTop() + views.get("lblremarkstitle").vw.getHeight())+(5d * scale)));
views.get("pnlremarksanchor").vw.setHeight((int)((views.get("pnlremarks").vw.getHeight())-(1d / 100 * height) - ((views.get("lblremarkstitle").vw.getTop() + views.get("lblremarkstitle").vw.getHeight())+(5d * scale))));
views.get("pnlremarksanchor").vw.setLeft((int)((1d / 100 * width)));
views.get("pnlremarksanchor").vw.setWidth((int)((views.get("pnlremarks").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("txtremarks").vw.setTop((int)((1d / 100 * height)));
views.get("txtremarks").vw.setHeight((int)((views.get("pnlremarksanchor").vw.getHeight())-(1d / 100 * height) - ((1d / 100 * height))));
views.get("txtremarks").vw.setLeft((int)((1d / 100 * width)));
views.get("txtremarks").vw.setWidth((int)((views.get("pnlremarksanchor").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("btnsaveupdate").vw.setLeft((int)((2d / 100 * width)));
views.get("btnsaveupdate").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("btnsaveupdate").vw.setTop((int)((views.get("pnlremarks").vw.getTop() + views.get("pnlremarks").vw.getHeight())+(7d * scale)));
views.get("btnsaveupdate").vw.setHeight((int)((views.get("pnlmain").vw.getHeight())-(1d / 100 * height) - ((views.get("pnlremarks").vw.getTop() + views.get("pnlremarks").vw.getHeight())+(7d * scale))));
views.get("pnlmaintimer").vw.setLeft((int)(0d));
views.get("pnlmaintimer").vw.setLeft((int)((0d / 100 * width)));
views.get("pnlmaintimer").vw.setWidth((int)((100d / 100 * width) - ((0d / 100 * width))));
views.get("pnlmaintimer").vw.setTop((int)((0d / 100 * height)));
views.get("pnlmaintimer").vw.setHeight((int)((100d / 100 * height) - ((0d / 100 * height))));
views.get("pnltimer").vw.setLeft((int)((3d / 100 * width)));
views.get("pnltimer").vw.setWidth((int)((views.get("pnlmaintimer").vw.getWidth())-(3d / 100 * width) - ((3d / 100 * width))));
views.get("pnltimer").vw.setTop((int)((20d / 100 * height)));
views.get("pnltimer").vw.setHeight((int)((views.get("pnlmaintimer").vw.getHeight())-(45d / 100 * height) - ((20d / 100 * height))));
views.get("pnlstopwatch").vw.setLeft((int)((3d / 100 * width)));
views.get("pnlstopwatch").vw.setWidth((int)((views.get("pnltimer").vw.getWidth())-(3d / 100 * width) - ((3d / 100 * width))));
views.get("pnlstopwatch").vw.setTop((int)((10d * scale)));
views.get("pnlstopwatch").vw.setHeight((int)((views.get("pnltimer").vw.getHeight())-(25d / 100 * height) - ((10d * scale))));
views.get("btnreset").vw.setLeft((int)((3d / 100 * width)));
views.get("btnreset").vw.setWidth((int)((views.get("pnltimer").vw.getWidth())-(3d / 100 * width) - ((3d / 100 * width))));
views.get("btnreset").vw.setTop((int)((views.get("pnlstopwatch").vw.getTop() + views.get("pnlstopwatch").vw.getHeight())+(5d * scale)));
views.get("btnstart").vw.setLeft((int)((3d / 100 * width)));
views.get("btnstart").vw.setWidth((int)((32d / 100 * width) - ((3d / 100 * width))));
views.get("btnpause").vw.setLeft((int)((views.get("btnstart").vw.getLeft() + views.get("btnstart").vw.getWidth())+(5d * scale)));
views.get("btnpause").vw.setWidth((int)((views.get("pnltimer").vw.getWidth())-(33d / 100 * width) - ((views.get("btnstart").vw.getLeft() + views.get("btnstart").vw.getWidth())+(5d * scale))));
views.get("btnstop").vw.setLeft((int)((views.get("btnpause").vw.getLeft() + views.get("btnpause").vw.getWidth())+(5d * scale)));
views.get("btnstop").vw.setWidth((int)((views.get("pnltimer").vw.getWidth())-(3d / 100 * width) - ((views.get("btnpause").vw.getLeft() + views.get("btnpause").vw.getWidth())+(5d * scale))));
views.get("btnstart").vw.setTop((int)((views.get("btnreset").vw.getTop() + views.get("btnreset").vw.getHeight())+(10d * scale)));
views.get("btnstart").vw.setHeight((int)((views.get("pnltimer").vw.getHeight())-(10d / 100 * height) - ((views.get("btnreset").vw.getTop() + views.get("btnreset").vw.getHeight())+(10d * scale))));
views.get("btnpause").vw.setTop((int)((views.get("btnreset").vw.getTop() + views.get("btnreset").vw.getHeight())+(10d * scale)));
views.get("btnpause").vw.setHeight((int)((views.get("pnltimer").vw.getHeight())-(10d / 100 * height) - ((views.get("btnreset").vw.getTop() + views.get("btnreset").vw.getHeight())+(10d * scale))));
views.get("btnstop").vw.setTop((int)((views.get("btnreset").vw.getTop() + views.get("btnreset").vw.getHeight())+(10d * scale)));
views.get("btnstop").vw.setHeight((int)((views.get("pnltimer").vw.getHeight())-(10d / 100 * height) - ((views.get("btnreset").vw.getTop() + views.get("btnreset").vw.getHeight())+(10d * scale))));
views.get("btncancel").vw.setLeft((int)((3d / 100 * width)));
views.get("btncancel").vw.setWidth((int)((views.get("pnltimer").vw.getWidth())-(60d / 100 * width) - ((3d / 100 * width))));
views.get("btncancel").vw.setTop((int)((views.get("btnstart").vw.getTop() + views.get("btnstart").vw.getHeight())+(15d * scale)));
views.get("btncancel").vw.setHeight((int)((views.get("pnltimer").vw.getHeight())-(2d / 100 * height) - ((views.get("btnstart").vw.getTop() + views.get("btnstart").vw.getHeight())+(15d * scale))));
views.get("btnok").vw.setLeft((int)((60d / 100 * width)));
views.get("btnok").vw.setWidth((int)((views.get("pnltimer").vw.getWidth())-(3d / 100 * width) - ((60d / 100 * width))));
views.get("btnok").vw.setTop((int)((views.get("btnstart").vw.getTop() + views.get("btnstart").vw.getHeight())+(15d * scale)));
views.get("btnok").vw.setHeight((int)((views.get("pnltimer").vw.getHeight())-(2d / 100 * height) - ((views.get("btnstart").vw.getTop() + views.get("btnstart").vw.getHeight())+(15d * scale))));

}
}