package bwsi.PumpOperations.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_problemrecords{

public static void LS_general(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
anywheresoftware.b4a.keywords.LayoutBuilder.scaleAll(views);
views.get("pnlmain").vw.setTop((int)((1d / 100 * height)));
views.get("pnlmain").vw.setHeight((int)((140d / 100 * height) - ((1d / 100 * height))));
views.get("pnlmain").vw.setLeft((int)((0d / 100 * width)));
views.get("pnlmain").vw.setWidth((int)((100d / 100 * width) - ((0d / 100 * width))));
views.get("pnltime").vw.setTop((int)((1d / 100 * height)));
views.get("pnltime").vw.setHeight((int)((views.get("pnlmain").vw.getHeight())-(110d / 100 * height) - ((1d / 100 * height))));
views.get("pnltime").vw.setLeft((int)((2d / 100 * width)));
views.get("pnltime").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("lbltimetitle").vw.setLeft((int)((0d / 100 * width)));
views.get("lbltimetitle").vw.setWidth((int)((views.get("pnltime").vw.getWidth()) - ((0d / 100 * width))));
views.get("lbltimetitle").vw.setTop((int)(0d));
views.get("lbllabel1").vw.setLeft((int)((2d / 100 * width)));
views.get("lbllabel1").vw.setTop((int)((views.get("lbltimetitle").vw.getTop() + views.get("lbltimetitle").vw.getHeight())+(5d * scale)));
views.get("pnltimefromanchor").vw.setTop((int)((views.get("lbltimetitle").vw.getTop() + views.get("lbltimetitle").vw.getHeight())+(5d * scale)));
views.get("pnltimefromanchor").vw.setTop((int)((views.get("lbllabel1").vw.getTop() + views.get("lbllabel1").vw.getHeight()/2) - (views.get("pnltimefromanchor").vw.getHeight() / 2)));
views.get("pnltimefromanchor").vw.setLeft((int)((views.get("lbllabel1").vw.getLeft() + views.get("lbllabel1").vw.getWidth())+(5d * scale)));
views.get("pnltimefromanchor").vw.setWidth((int)((views.get("pnltime").vw.getWidth())-(50d / 100 * width) - ((views.get("lbllabel1").vw.getLeft() + views.get("lbllabel1").vw.getWidth())+(5d * scale))));
views.get("msktimefrom").vw.setTop((int)((0.5d / 100 * height)));
views.get("msktimefrom").vw.setHeight((int)((views.get("pnltimefromanchor").vw.getHeight())-(0.5d / 100 * height) - ((0.5d / 100 * height))));
views.get("msktimefrom").vw.setLeft((int)((1d / 100 * width)));
views.get("msktimefrom").vw.setWidth((int)((views.get("pnltimefromanchor").vw.getWidth())-(19d * scale) - ((1d / 100 * width))));
views.get("pnlstyle1").vw.setTop((int)((views.get("pnltimefromanchor").vw.getTop())));
views.get("pnlstyle1").vw.setLeft((int)((views.get("pnltimefromanchor").vw.getLeft() + views.get("pnltimefromanchor").vw.getWidth())-(18d * scale)));
views.get("pnlstyle1").vw.setWidth((int)((views.get("pnltime").vw.getWidth())-(2d / 100 * width) - ((views.get("pnltimefromanchor").vw.getLeft() + views.get("pnltimefromanchor").vw.getWidth())-(18d * scale))));
views.get("lbltime1").vw.setLeft((int)((1d / 100 * width)));
views.get("lbltime1").vw.setWidth((int)((views.get("pnlstyle1").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("lbltime1").vw.setTop((int)((views.get("msktimefrom").vw.getTop() + views.get("msktimefrom").vw.getHeight()/2) - (views.get("lbltime1").vw.getHeight() / 2)));
views.get("pnlcover1").vw.setLeft((int)((views.get("pnlstyle1").vw.getLeft())));
views.get("pnlcover1").vw.setTop((int)((views.get("pnltimefromanchor").vw.getTop())));
views.get("lbllabel2").vw.setLeft((int)((2d / 100 * width)));
views.get("lbllabel2").vw.setTop((int)((views.get("lbllabel1").vw.getTop() + views.get("lbllabel1").vw.getHeight())+(5d * scale)));
views.get("pnltimetoanchor").vw.setTop((int)((views.get("lbllabel1").vw.getTop() + views.get("lbllabel1").vw.getHeight())+(5d * scale)));
views.get("pnltimetoanchor").vw.setTop((int)((views.get("lbllabel2").vw.getTop() + views.get("lbllabel2").vw.getHeight()/2) - (views.get("pnltimetoanchor").vw.getHeight() / 2)));
views.get("pnltimetoanchor").vw.setLeft((int)((views.get("lbllabel2").vw.getLeft() + views.get("lbllabel2").vw.getWidth())+(5d * scale)));
views.get("pnltimetoanchor").vw.setWidth((int)((views.get("pnltime").vw.getWidth())-(50d / 100 * width) - ((views.get("lbllabel2").vw.getLeft() + views.get("lbllabel2").vw.getWidth())+(5d * scale))));
views.get("msktimeto").vw.setTop((int)((0.5d / 100 * height)));
views.get("msktimeto").vw.setHeight((int)((views.get("pnltimetoanchor").vw.getHeight())-(0.5d / 100 * height) - ((0.5d / 100 * height))));
views.get("msktimeto").vw.setLeft((int)((1d / 100 * width)));
views.get("msktimeto").vw.setWidth((int)((views.get("pnltimetoanchor").vw.getWidth())-(19d * scale) - ((1d / 100 * width))));
views.get("pnlstyle2").vw.setTop((int)((views.get("pnltimetoanchor").vw.getTop())));
views.get("pnlstyle2").vw.setLeft((int)((views.get("pnltimetoanchor").vw.getLeft() + views.get("pnltimetoanchor").vw.getWidth())-(18d * scale)));
views.get("pnlstyle2").vw.setWidth((int)((views.get("pnltime").vw.getWidth())-(2d / 100 * width) - ((views.get("pnltimetoanchor").vw.getLeft() + views.get("pnltimetoanchor").vw.getWidth())-(18d * scale))));
views.get("lbltime2").vw.setLeft((int)((1d / 100 * width)));
views.get("lbltime2").vw.setWidth((int)((views.get("pnlstyle2").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("lbltime2").vw.setTop((int)((views.get("msktimeto").vw.getTop() + views.get("msktimeto").vw.getHeight()/2) - (views.get("lbltime2").vw.getHeight() / 2)));
views.get("pnlcover2").vw.setLeft((int)((views.get("pnlstyle2").vw.getLeft())));
views.get("pnlcover2").vw.setTop((int)((views.get("pnltimetoanchor").vw.getTop())));
views.get("pnlarea").vw.setLeft((int)((1.5d / 100 * width)));
views.get("pnlarea").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(1.5d / 100 * width) - ((1.5d / 100 * width))));
views.get("pnlarea").vw.setTop((int)((views.get("pnltime").vw.getTop() + views.get("pnltime").vw.getHeight())+(5d * scale)));
views.get("pnlarea").vw.setHeight((int)((views.get("pnlmain").vw.getHeight())-(85d / 100 * height) - ((views.get("pnltime").vw.getTop() + views.get("pnltime").vw.getHeight())+(5d * scale))));
views.get("lblareatitle").vw.setLeft((int)((0d / 100 * width)));
views.get("lblareatitle").vw.setWidth((int)((views.get("pnlarea").vw.getWidth()) - ((0d / 100 * width))));
views.get("lblareatitle").vw.setTop((int)(0d));
views.get("lbl1").vw.setLeft((int)((2d / 100 * width)));
views.get("lbl1").vw.setTop((int)((views.get("lblareatitle").vw.getTop() + views.get("lblareatitle").vw.getHeight())+(5d * scale)));
views.get("pnlpumpareaanchor").vw.setLeft((int)((views.get("lbl1").vw.getLeft() + views.get("lbl1").vw.getWidth())+(5d * scale)));
views.get("pnlpumpareaanchor").vw.setWidth((int)((views.get("pnlarea").vw.getWidth())-(2d / 100 * width) - ((views.get("lbl1").vw.getLeft() + views.get("lbl1").vw.getWidth())+(5d * scale))));
views.get("pnlpumpareaanchor").vw.setTop((int)((views.get("lblareatitle").vw.getTop() + views.get("lblareatitle").vw.getHeight())+(5d * scale)));
views.get("cbopumparea").vw.setLeft((int)((2d / 100 * width)));
views.get("cbopumparea").vw.setWidth((int)((views.get("pnlpumpareaanchor").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("cbopumparea").vw.setTop((int)((0.5d / 100 * height)));
views.get("cbopumparea").vw.setHeight((int)((views.get("pnlpumpareaanchor").vw.getHeight())-(0.5d / 100 * height) - ((0.5d / 100 * height))));
views.get("chkcritical").vw.setTop((int)((views.get("lbl1").vw.getTop() + views.get("lbl1").vw.getHeight())+(10d * scale)));
views.get("chkcritical").vw.setLeft((int)((2d / 100 * width)));
views.get("chkcritical").vw.setWidth((int)((views.get("pnlarea").vw.getWidth())-(60d / 100 * width) - ((2d / 100 * width))));
views.get("pnlprobtitle").vw.setTop((int)((views.get("pnlarea").vw.getTop() + views.get("pnlarea").vw.getHeight())+(5d * scale)));
views.get("pnlprobtitle").vw.setHeight((int)((views.get("pnlmain").vw.getHeight())-(68d / 100 * height) - ((views.get("pnlarea").vw.getTop() + views.get("pnlarea").vw.getHeight())+(5d * scale))));
views.get("pnlprobtitle").vw.setLeft((int)((1.5d / 100 * width)));
views.get("pnlprobtitle").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(1.5d / 100 * width) - ((1.5d / 100 * width))));
views.get("lblprobtitle").vw.setTop((int)((0d / 100 * height)));
views.get("lblprobtitle").vw.setLeft((int)((0d / 100 * width)));
views.get("lblprobtitle").vw.setWidth((int)((views.get("pnlprobtitle").vw.getWidth()) - ((0d / 100 * width))));
views.get("pnlprobtitleanchor").vw.setLeft((int)((2d / 100 * width)));
views.get("pnlprobtitleanchor").vw.setWidth((int)((views.get("pnlprobtitle").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("pnlprobtitleanchor").vw.setTop((int)((views.get("lblprobtitle").vw.getTop() + views.get("lblprobtitle").vw.getHeight())+(3d * scale)));
views.get("pnlprobtitleanchor").vw.setHeight((int)((views.get("pnlprobtitle").vw.getHeight())-(1d / 100 * height) - ((views.get("lblprobtitle").vw.getTop() + views.get("lblprobtitle").vw.getHeight())+(3d * scale))));
views.get("txtprobtitle").vw.setLeft((int)((2d / 100 * width)));
views.get("txtprobtitle").vw.setWidth((int)((views.get("pnlprobtitleanchor").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("txtprobtitle").vw.setTop((int)((1d / 100 * height)));
views.get("txtprobtitle").vw.setHeight((int)((views.get("pnlprobtitleanchor").vw.getHeight())-(1d / 100 * height) - ((1d / 100 * height))));
views.get("pnlprobdetails").vw.setLeft((int)((1.5d / 100 * width)));
views.get("pnlprobdetails").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(1.5d / 100 * width) - ((1.5d / 100 * width))));
views.get("pnlprobdetails").vw.setTop((int)((views.get("pnlprobtitle").vw.getTop() + views.get("pnlprobtitle").vw.getHeight())+(5d * scale)));
views.get("pnlprobdetails").vw.setHeight((int)((views.get("pnlmain").vw.getHeight())-(45d / 100 * height) - ((views.get("pnlprobtitle").vw.getTop() + views.get("pnlprobtitle").vw.getHeight())+(5d * scale))));
views.get("lblprobdesctitle").vw.setTop((int)((0d / 100 * height)));
views.get("lblprobdesctitle").vw.setLeft((int)((0d / 100 * width)));
views.get("lblprobdesctitle").vw.setWidth((int)((views.get("pnlprobdetails").vw.getWidth()) - ((0d / 100 * width))));
views.get("pnlprobdescanchor").vw.setLeft((int)((2d / 100 * width)));
views.get("pnlprobdescanchor").vw.setWidth((int)((views.get("pnlprobdetails").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("pnlprobdescanchor").vw.setTop((int)((views.get("lblprobdesctitle").vw.getTop() + views.get("lblprobdesctitle").vw.getHeight())+(3d * scale)));
views.get("pnlprobdescanchor").vw.setHeight((int)((views.get("pnlprobdetails").vw.getHeight())-(1d / 100 * height) - ((views.get("lblprobdesctitle").vw.getTop() + views.get("lblprobdesctitle").vw.getHeight())+(3d * scale))));
views.get("txtprobdetails").vw.setLeft((int)((2d / 100 * width)));
views.get("txtprobdetails").vw.setWidth((int)((views.get("pnlprobdescanchor").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("txtprobdetails").vw.setTop((int)((1d / 100 * height)));
views.get("txtprobdetails").vw.setHeight((int)((views.get("pnlprobdescanchor").vw.getHeight())-(1d / 100 * height) - ((1d / 100 * height))));
views.get("pnlactiontaken").vw.setTop((int)((views.get("pnlprobdetails").vw.getTop() + views.get("pnlprobdetails").vw.getHeight())+(5d * scale)));
views.get("pnlactiontaken").vw.setHeight((int)((views.get("pnlmain").vw.getHeight())-(16d / 100 * height) - ((views.get("pnlprobdetails").vw.getTop() + views.get("pnlprobdetails").vw.getHeight())+(5d * scale))));
views.get("pnlactiontaken").vw.setLeft((int)((1.5d / 100 * width)));
views.get("pnlactiontaken").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(1.5d / 100 * width) - ((1.5d / 100 * width))));
views.get("lblactiontakentitle").vw.setTop((int)((0d / 100 * height)));
views.get("lblactiontakentitle").vw.setLeft((int)((0d / 100 * width)));
views.get("lblactiontakentitle").vw.setWidth((int)((views.get("pnlactiontaken").vw.getWidth()) - ((0d / 100 * width))));
views.get("chkwassolved").vw.setTop((int)((views.get("lblactiontakentitle").vw.getTop() + views.get("lblactiontakentitle").vw.getHeight())+(5d * scale)));
views.get("chkwassolved").vw.setLeft((int)((2d / 100 * width)));
views.get("chkwassolved").vw.setWidth((int)((views.get("pnlactiontaken").vw.getWidth())-(65d / 100 * width) - ((2d / 100 * width))));
views.get("pnlactiontakenanchor").vw.setLeft((int)((2d / 100 * width)));
views.get("pnlactiontakenanchor").vw.setWidth((int)((views.get("pnlactiontaken").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("pnlactiontakenanchor").vw.setTop((int)((views.get("chkwassolved").vw.getTop() + views.get("chkwassolved").vw.getHeight())+(10d * scale)));
views.get("pnlactiontakenanchor").vw.setHeight((int)((views.get("pnlactiontaken").vw.getHeight())-(1d / 100 * height) - ((views.get("chkwassolved").vw.getTop() + views.get("chkwassolved").vw.getHeight())+(10d * scale))));
views.get("txtactiontaken").vw.setLeft((int)((2d / 100 * width)));
views.get("txtactiontaken").vw.setWidth((int)((views.get("pnlactiontakenanchor").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("txtactiontaken").vw.setTop((int)((1d / 100 * height)));
views.get("txtactiontaken").vw.setHeight((int)((views.get("pnlactiontakenanchor").vw.getHeight())-(1d / 100 * height) - ((1d / 100 * height))));
views.get("btnsaveupdate").vw.setLeft((int)((2d / 100 * width)));
views.get("btnsaveupdate").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("btnsaveupdate").vw.setTop((int)((views.get("pnlactiontaken").vw.getTop() + views.get("pnlactiontaken").vw.getHeight())+(10d * scale)));
views.get("btnsaveupdate").vw.setHeight((int)((views.get("pnlmain").vw.getHeight())-(2d / 100 * height) - ((views.get("pnlactiontaken").vw.getTop() + views.get("pnlactiontaken").vw.getHeight())+(10d * scale))));

}
}