package bwsi.PumpOperations.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_sasjofindings{

public static void LS_general(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
anywheresoftware.b4a.keywords.LayoutBuilder.scaleAll(views);
views.get("toolbar").vw.setTop((int)((0d * scale)));
if ((anywheresoftware.b4a.keywords.LayoutBuilder.getScreenSize()>6.5d)) { 
;
views.get("toolbar").vw.setHeight((int)((64d * scale)));
;}else{ 
;
if ((BA.ObjectToBoolean( String.valueOf(anywheresoftware.b4a.keywords.LayoutBuilder.isPortrait())))) { 
;
views.get("toolbar").vw.setHeight((int)((50d * scale)));
;}else{ 
;
views.get("toolbar").vw.setHeight((int)((42d * scale)));
;};
;};
views.get("pnlmain").vw.setLeft((int)(0d));
views.get("pnlmain").vw.setTop((int)((views.get("toolbar").vw.getTop() + views.get("toolbar").vw.getHeight())));
views.get("pnlmain").vw.setWidth((int)((100d / 100 * width)));
views.get("pnlmain").vw.setHeight((int)((100d / 100 * height)-(views.get("toolbar").vw.getHeight())));
views.get("pnljodetails").vw.setTop((int)((1d / 100 * height)));
views.get("pnljodetails").vw.setLeft((int)((1d / 100 * width)));
views.get("pnljodetails").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("lbljodetailstitle").vw.setLeft((int)((0d / 100 * width)));
views.get("lbljodetailstitle").vw.setWidth((int)((views.get("pnljodetails").vw.getWidth()) - ((0d / 100 * width))));
views.get("pnljodetails").vw.setHeight((int)((33d / 100 * height)));
views.get("lbljodetailstitle").vw.setLeft((int)((0d / 100 * width)));
views.get("lbljodetailstitle").vw.setWidth((int)((views.get("pnljodetails").vw.getWidth()) - ((0d / 100 * width))));
views.get("label4").vw.setTop((int)((views.get("lbljodetailstitle").vw.getTop() + views.get("lbljodetailstitle").vw.getHeight())+(5d * scale)));
views.get("pnljodetstyle1").vw.setTop((int)((views.get("lbljodetailstitle").vw.getTop() + views.get("lbljodetailstitle").vw.getHeight())+(5d * scale)));
views.get("pnljodetstyle1").vw.setLeft((int)((views.get("label4").vw.getLeft() + views.get("label4").vw.getWidth())+(2d * scale)));
views.get("pnljodetstyle1").vw.setWidth((int)((views.get("pnljodetails").vw.getWidth())-(2d / 100 * width) - ((views.get("label4").vw.getLeft() + views.get("label4").vw.getWidth())+(2d * scale))));
views.get("lbljonum").vw.setLeft((int)((2d / 100 * width)));
views.get("lbljonum").vw.setWidth((int)((views.get("pnljodetstyle1").vw.getWidth())-(1d / 100 * width) - ((2d / 100 * width))));
views.get("lbljonum").vw.setTop((int)((0.25d / 100 * height)));
views.get("lbljonum").vw.setHeight((int)((views.get("pnljodetstyle1").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("pnljodetstyle2").vw.setTop((int)((views.get("pnljodetstyle1").vw.getTop() + views.get("pnljodetstyle1").vw.getHeight())+(1d * scale)));
views.get("pnljodetstyle2").vw.setLeft((int)((views.get("label4").vw.getLeft() + views.get("label4").vw.getWidth())+(2d * scale)));
views.get("pnljodetstyle2").vw.setWidth((int)((views.get("pnljodetails").vw.getWidth())-(2d / 100 * width) - ((views.get("label4").vw.getLeft() + views.get("label4").vw.getWidth())+(2d * scale))));
views.get("lbljocat").vw.setLeft((int)((2d / 100 * width)));
views.get("lbljocat").vw.setWidth((int)((views.get("pnljodetstyle2").vw.getWidth())-(1d / 100 * width) - ((2d / 100 * width))));
views.get("lbljocat").vw.setTop((int)((0.25d / 100 * height)));
views.get("lbljocat").vw.setHeight((int)((views.get("pnljodetstyle2").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("label5").vw.setTop((int)((views.get("pnljodetstyle2").vw.getTop() + views.get("pnljodetstyle2").vw.getHeight())+(3d * scale)));
views.get("pnljodetstyle3").vw.setTop((int)((views.get("pnljodetstyle2").vw.getTop() + views.get("pnljodetstyle2").vw.getHeight())+(3d * scale)));
views.get("pnljodetstyle3").vw.setLeft((int)((views.get("label5").vw.getLeft() + views.get("label5").vw.getWidth())+(2d * scale)));
views.get("pnljodetstyle3").vw.setWidth((int)((views.get("pnljodetails").vw.getWidth())-(2d / 100 * width) - ((views.get("label5").vw.getLeft() + views.get("label5").vw.getWidth())+(2d * scale))));
views.get("lblappnum").vw.setLeft((int)((2d / 100 * width)));
views.get("lblappnum").vw.setWidth((int)((views.get("pnljodetstyle3").vw.getWidth())-(1d / 100 * width) - ((2d / 100 * width))));
views.get("lblappnum").vw.setTop((int)((0.25d / 100 * height)));
views.get("lblappnum").vw.setHeight((int)((views.get("pnljodetstyle3").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("label6").vw.setTop((int)((views.get("pnljodetstyle3").vw.getTop() + views.get("pnljodetstyle3").vw.getHeight())+(3d * scale)));
views.get("pnljodetstyle4").vw.setTop((int)((views.get("pnljodetstyle3").vw.getTop() + views.get("pnljodetstyle3").vw.getHeight())+(3d * scale)));
views.get("pnljodetstyle4").vw.setLeft((int)((views.get("label6").vw.getLeft() + views.get("label6").vw.getWidth())+(2d * scale)));
views.get("pnljodetstyle4").vw.setWidth((int)((views.get("pnljodetails").vw.getWidth())-(2d / 100 * width) - ((views.get("label6").vw.getLeft() + views.get("label6").vw.getWidth())+(2d * scale))));
views.get("lblcustname").vw.setLeft((int)((2d / 100 * width)));
views.get("lblcustname").vw.setWidth((int)((views.get("pnljodetstyle4").vw.getWidth())-(1d / 100 * width) - ((2d / 100 * width))));
views.get("lblcustname").vw.setTop((int)((0.25d / 100 * height)));
views.get("lblcustname").vw.setHeight((int)((views.get("pnljodetstyle4").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("pnljodetstyle5").vw.setTop((int)((views.get("pnljodetstyle4").vw.getTop() + views.get("pnljodetstyle4").vw.getHeight())+(3d * scale)));
views.get("pnljodetstyle5").vw.setLeft((int)((views.get("label6").vw.getLeft())));
views.get("pnljodetstyle5").vw.setWidth((int)((views.get("pnljodetails").vw.getWidth())-(2d / 100 * width) - ((views.get("label6").vw.getLeft()))));
views.get("lblcustaddress").vw.setLeft((int)((2d / 100 * width)));
views.get("lblcustaddress").vw.setWidth((int)((views.get("pnljodetstyle5").vw.getWidth())-(1d / 100 * width) - ((2d / 100 * width))));
views.get("lblcustaddress").vw.setTop((int)((0.25d / 100 * height)));
views.get("lblcustaddress").vw.setHeight((int)((views.get("pnljodetstyle5").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("pnlfindings").vw.setTop((int)((35d / 100 * height)));
views.get("pnlfindings").vw.setLeft((int)((1d / 100 * width)));
views.get("pnlfindings").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("pnlfindings").vw.setHeight((int)((28d / 100 * height)));
views.get("lblfindingstitle").vw.setLeft((int)((0d / 100 * width)));
views.get("lblfindingstitle").vw.setWidth((int)((views.get("pnlfindings").vw.getWidth()) - ((0d / 100 * width))));
views.get("label1").vw.setTop((int)((views.get("lblfindingstitle").vw.getTop() + views.get("lblfindingstitle").vw.getHeight())+(5d * scale)));
views.get("label1").vw.setLeft((int)((3d / 100 * width)));
views.get("pnlacctclassanchor").vw.setTop((int)((views.get("lblfindingstitle").vw.getTop() + views.get("lblfindingstitle").vw.getHeight())+(5d * scale)));
views.get("pnlacctclassanchor").vw.setLeft((int)((views.get("label1").vw.getLeft() + views.get("label1").vw.getWidth())+(5d * scale)));
views.get("pnlacctclassanchor").vw.setWidth((int)((views.get("pnlfindings").vw.getWidth())-(3d / 100 * width) - ((views.get("label1").vw.getLeft() + views.get("label1").vw.getWidth())+(5d * scale))));
views.get("cboacctclass").vw.setLeft((int)((2d / 100 * width)));
views.get("cboacctclass").vw.setWidth((int)((views.get("pnlacctclassanchor").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("cboacctclass").vw.setTop((int)((0.25d / 100 * height)));
views.get("cboacctclass").vw.setHeight((int)((views.get("pnlacctclassanchor").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("label2").vw.setTop((int)((views.get("label1").vw.getTop() + views.get("label1").vw.getHeight())+(5d * scale)));
views.get("label2").vw.setLeft((int)((3d / 100 * width)));
views.get("pnlsubclassanchor").vw.setTop((int)((views.get("label1").vw.getTop() + views.get("label1").vw.getHeight())+(5d * scale)));
views.get("pnlsubclassanchor").vw.setLeft((int)((views.get("label2").vw.getLeft() + views.get("label2").vw.getWidth())+(5d * scale)));
views.get("pnlsubclassanchor").vw.setWidth((int)((views.get("pnlfindings").vw.getWidth())-(3d / 100 * width) - ((views.get("label2").vw.getLeft() + views.get("label2").vw.getWidth())+(5d * scale))));
views.get("cbosubclass").vw.setLeft((int)((2d / 100 * width)));
views.get("cbosubclass").vw.setWidth((int)((views.get("pnlsubclassanchor").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("cbosubclass").vw.setTop((int)((0.25d / 100 * height)));
views.get("cbosubclass").vw.setHeight((int)((views.get("pnlsubclassanchor").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("label3").vw.setTop((int)((views.get("label2").vw.getTop() + views.get("label2").vw.getHeight())+(5d * scale)));
views.get("label3").vw.setLeft((int)((3d / 100 * width)));
views.get("pnlcontypeanchor").vw.setTop((int)((views.get("label2").vw.getTop() + views.get("label2").vw.getHeight())+(5d * scale)));
views.get("pnlcontypeanchor").vw.setLeft((int)((views.get("label3").vw.getLeft() + views.get("label3").vw.getWidth())+(5d * scale)));
views.get("pnlcontypeanchor").vw.setWidth((int)((views.get("pnlfindings").vw.getWidth())-(3d / 100 * width) - ((views.get("label3").vw.getLeft() + views.get("label3").vw.getWidth())+(5d * scale))));
views.get("cbocontype").vw.setLeft((int)((2d / 100 * width)));
views.get("cbocontype").vw.setWidth((int)((views.get("pnlcontypeanchor").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("cbocontype").vw.setTop((int)((0.25d / 100 * height)));
views.get("cbocontype").vw.setHeight((int)((views.get("pnlcontypeanchor").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("pnlremarks").vw.setTop((int)((views.get("pnlfindings").vw.getTop() + views.get("pnlfindings").vw.getHeight())+(7d * scale)));
views.get("pnlremarks").vw.setHeight((int)((views.get("pnlmain").vw.getHeight())-(10d / 100 * height) - ((views.get("pnlfindings").vw.getTop() + views.get("pnlfindings").vw.getHeight())+(7d * scale))));
views.get("pnlremarks").vw.setLeft((int)((1d / 100 * width)));
views.get("pnlremarks").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("lblremarkstitle").vw.setLeft((int)((0d / 100 * width)));
views.get("lblremarkstitle").vw.setWidth((int)((views.get("pnlremarks").vw.getWidth()) - ((0d / 100 * width))));
views.get("pnlremarksanchor").vw.setLeft((int)((2d / 100 * width)));
views.get("pnlremarksanchor").vw.setWidth((int)((views.get("pnlremarks").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("pnlremarksanchor").vw.setTop((int)((views.get("lblremarkstitle").vw.getTop() + views.get("lblremarkstitle").vw.getHeight())+(5d * scale)));
views.get("pnlremarksanchor").vw.setHeight((int)((views.get("pnlremarks").vw.getHeight())-(1d / 100 * height) - ((views.get("lblremarkstitle").vw.getTop() + views.get("lblremarkstitle").vw.getHeight())+(5d * scale))));
views.get("txtremarks").vw.setLeft((int)((2d / 100 * width)));
views.get("txtremarks").vw.setWidth((int)((views.get("pnlremarksanchor").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("txtremarks").vw.setTop((int)((1d / 100 * height)));
views.get("txtremarks").vw.setHeight((int)((views.get("pnlremarksanchor").vw.getHeight())-(1d / 100 * height) - ((1d / 100 * height))));
views.get("btnsaveupdate").vw.setLeft((int)((1d / 100 * width)));
views.get("btnsaveupdate").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("btnsaveupdate").vw.setTop((int)((views.get("pnlremarks").vw.getTop() + views.get("pnlremarks").vw.getHeight())+(10d * scale)));
views.get("btnsaveupdate").vw.setHeight((int)((views.get("pnlmain").vw.getHeight())-(1.5d / 100 * height) - ((views.get("pnlremarks").vw.getTop() + views.get("pnlremarks").vw.getHeight())+(10d * scale))));
views.get("pnlsignature").vw.setLeft((int)((0d / 100 * width)));
views.get("pnlsignature").vw.setWidth((int)((100d / 100 * width) - ((0d / 100 * width))));
views.get("pnlsignature").vw.setTop((int)((0d / 100 * height)));
views.get("pnlsignature").vw.setHeight((int)((100d / 100 * height) - ((0d / 100 * height))));
views.get("pnlmainsigbg").vw.setLeft((int)((2d / 100 * width)));
views.get("pnlmainsigbg").vw.setWidth((int)((views.get("pnlsignature").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("pnlmainsigbg").vw.setTop((int)((20d / 100 * height)));
views.get("pnlmainsigbg").vw.setHeight((int)((views.get("pnlsignature").vw.getHeight())-(30d / 100 * height) - ((20d / 100 * height))));
views.get("lblcustsignature").vw.setLeft((int)((0d / 100 * width)));
views.get("lblcustsignature").vw.setWidth((int)((views.get("pnlmainsigbg").vw.getWidth()) - ((0d / 100 * width))));
views.get("lblcustsignature").vw.setTop((int)((0d / 100 * height)));
views.get("pnlsigbg").vw.setLeft((int)((3d / 100 * width)));
views.get("pnlsigbg").vw.setWidth((int)((views.get("pnlmainsigbg").vw.getWidth())-(3d / 100 * width) - ((3d / 100 * width))));
views.get("pnlsigbg").vw.setTop((int)((views.get("lblcustsignature").vw.getTop() + views.get("lblcustsignature").vw.getHeight())+(5d * scale)));
views.get("pnlsigbg").vw.setHeight((int)((views.get("pnlmainsigbg").vw.getHeight())-(10d / 100 * height) - ((views.get("lblcustsignature").vw.getTop() + views.get("lblcustsignature").vw.getHeight())+(5d * scale))));
views.get("btnconfirmsig").vw.setLeft((int)((views.get("pnlsigbg").vw.getLeft())));
views.get("btnconfirmsig").vw.setWidth((int)((views.get("pnlsigbg").vw.getLeft() + views.get("pnlsigbg").vw.getWidth()) - ((views.get("pnlsigbg").vw.getLeft()))));
views.get("btnconfirmsig").vw.setTop((int)((views.get("pnlsigbg").vw.getTop() + views.get("pnlsigbg").vw.getHeight())+(10d * scale)));
views.get("btnconfirmsig").vw.setHeight((int)((views.get("pnlmainsigbg").vw.getHeight())-(2d / 100 * height) - ((views.get("pnlsigbg").vw.getTop() + views.get("pnlsigbg").vw.getHeight())+(10d * scale))));
views.get("signaturepad").vw.setLeft((int)((1.5d / 100 * width)));
views.get("signaturepad").vw.setWidth((int)((views.get("pnlsigbg").vw.getWidth())-(1.5d / 100 * width) - ((1.5d / 100 * width))));
views.get("signaturepad").vw.setTop((int)((1.5d / 100 * height)));
views.get("signaturepad").vw.setHeight((int)((views.get("pnlsigbg").vw.getHeight())-(1.5d / 100 * height) - ((1.5d / 100 * height))));
views.get("pnlconfirmsig").vw.setLeft((int)((0d / 100 * width)));
views.get("pnlconfirmsig").vw.setWidth((int)((100d / 100 * width) - ((0d / 100 * width))));
views.get("pnlconfirmsig").vw.setTop((int)((0d / 100 * height)));
views.get("pnlconfirmsig").vw.setHeight((int)((100d / 100 * height) - ((0d / 100 * height))));
views.get("pnlmainsigbg2").vw.setLeft((int)((1d / 100 * width)));
views.get("pnlmainsigbg2").vw.setWidth((int)((views.get("pnlconfirmsig").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("pnlmainsigbg2").vw.setTop((int)((10d / 100 * height)));
views.get("pnlmainsigbg2").vw.setHeight((int)((views.get("pnlconfirmsig").vw.getHeight())-(10d / 100 * height) - ((10d / 100 * height))));
views.get("lblconfirmsig").vw.setLeft((int)((0d / 100 * width)));
views.get("lblconfirmsig").vw.setWidth((int)((views.get("pnlmainsigbg2").vw.getWidth()) - ((0d / 100 * width))));
views.get("lblconfirmsig").vw.setTop((int)((0d / 100 * height)));
views.get("pnlimagesig").vw.setLeft((int)((3d / 100 * width)));
views.get("pnlimagesig").vw.setWidth((int)((views.get("pnlmainsigbg2").vw.getWidth())-(3d / 100 * width) - ((3d / 100 * width))));
views.get("pnlimagesig").vw.setTop((int)((views.get("lblconfirmsig").vw.getTop() + views.get("lblconfirmsig").vw.getHeight())+(5d * scale)));
views.get("pnlimagesig").vw.setHeight((int)((views.get("pnlmainsigbg2").vw.getHeight())-(40d / 100 * height) - ((views.get("lblconfirmsig").vw.getTop() + views.get("lblconfirmsig").vw.getHeight())+(5d * scale))));
views.get("imgsignature").vw.setLeft((int)((2d / 100 * width)));
views.get("imgsignature").vw.setWidth((int)((views.get("pnlimagesig").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("imgsignature").vw.setTop((int)((2d / 100 * height)));
views.get("imgsignature").vw.setHeight((int)((views.get("pnlimagesig").vw.getHeight())-(2d / 100 * height) - ((2d / 100 * height))));
views.get("lblaccomplishedby").vw.setLeft((int)((2d / 100 * width)));
views.get("lblaccomplishedby").vw.setWidth((int)((views.get("pnlmainsigbg2").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("lblaccomplishedby").vw.setTop((int)((views.get("pnlimagesig").vw.getTop() + views.get("pnlimagesig").vw.getHeight())+(10d * scale)));
views.get("pnlplumberanchor").vw.setLeft((int)((2d / 100 * width)));
views.get("pnlplumberanchor").vw.setWidth((int)((views.get("pnlmainsigbg2").vw.getWidth())-(2d / 100 * width) - ((2d / 100 * width))));
views.get("pnlplumberanchor").vw.setTop((int)((views.get("lblaccomplishedby").vw.getTop() + views.get("lblaccomplishedby").vw.getHeight())+(2d * scale)));
views.get("spnplumbers").vw.setLeft((int)((1d / 100 * width)));
views.get("spnplumbers").vw.setWidth((int)((views.get("pnlplumberanchor").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("spnplumbers").vw.setTop((int)((0.5d / 100 * height)));
views.get("spnplumbers").vw.setHeight((int)((views.get("pnlplumberanchor").vw.getHeight())-(0.5d / 100 * height) - ((0.5d / 100 * height))));
views.get("lbldatetimestart").vw.setTop((int)((views.get("pnlplumberanchor").vw.getTop() + views.get("pnlplumberanchor").vw.getHeight())+(5d * scale)));
views.get("lbldatetimestart").vw.setLeft((int)((2d / 100 * width)));
views.get("pnlstartedanchor").vw.setTop((int)((views.get("lbldatetimestart").vw.getTop())));
views.get("pnlstartedanchor").vw.setLeft((int)((views.get("lbldatetimestart").vw.getLeft() + views.get("lbldatetimestart").vw.getWidth())+(5d * scale)));
views.get("pnlstartedanchor").vw.setWidth((int)((views.get("pnlmainsigbg2").vw.getWidth())-(2d / 100 * width) - ((views.get("lbldatetimestart").vw.getLeft() + views.get("lbldatetimestart").vw.getWidth())+(5d * scale))));
views.get("txtdatetimestarted").vw.setLeft((int)((1d / 100 * width)));
views.get("txtdatetimestarted").vw.setWidth((int)((views.get("pnlstartedanchor").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("txtdatetimestarted").vw.setTop((int)((0.25d / 100 * height)));
views.get("txtdatetimestarted").vw.setHeight((int)((views.get("pnlstartedanchor").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("lbldatetimefinished").vw.setTop((int)((views.get("lbldatetimestart").vw.getTop() + views.get("lbldatetimestart").vw.getHeight())+(5d * scale)));
views.get("lbldatetimefinished").vw.setLeft((int)((2d / 100 * width)));
views.get("pnlfinishedanchor").vw.setTop((int)((views.get("lbldatetimefinished").vw.getTop())));
views.get("pnlfinishedanchor").vw.setLeft((int)((views.get("lbldatetimestart").vw.getLeft() + views.get("lbldatetimestart").vw.getWidth())+(5d * scale)));
views.get("pnlfinishedanchor").vw.setWidth((int)((views.get("pnlmainsigbg2").vw.getWidth())-(2d / 100 * width) - ((views.get("lbldatetimestart").vw.getLeft() + views.get("lbldatetimestart").vw.getWidth())+(5d * scale))));
views.get("txtdatetimefinished").vw.setLeft((int)((1d / 100 * width)));
views.get("txtdatetimefinished").vw.setWidth((int)((views.get("pnlfinishedanchor").vw.getWidth())-(1d / 100 * width) - ((1d / 100 * width))));
views.get("txtdatetimefinished").vw.setTop((int)((0.25d / 100 * height)));
views.get("txtdatetimefinished").vw.setHeight((int)((views.get("pnlfinishedanchor").vw.getHeight())-(0.25d / 100 * height) - ((0.25d / 100 * height))));
views.get("btncancel").vw.setLeft((int)((3d / 100 * width)));
views.get("btncancel").vw.setWidth((int)((views.get("pnlmainsigbg2").vw.getWidth())-(65d / 100 * width) - ((3d / 100 * width))));
views.get("btncancel").vw.setTop((int)((views.get("pnlfinishedanchor").vw.getTop() + views.get("pnlfinishedanchor").vw.getHeight())+(10d * scale)));
views.get("btnclear").vw.setLeft((int)((36d / 100 * width)));
views.get("btnclear").vw.setWidth((int)((views.get("pnlmainsigbg2").vw.getWidth())-(32d / 100 * width) - ((36d / 100 * width))));
views.get("btnclear").vw.setTop((int)((views.get("pnlfinishedanchor").vw.getTop() + views.get("pnlfinishedanchor").vw.getHeight())+(10d * scale)));
views.get("btnok").vw.setLeft((int)((69d / 100 * width)));
views.get("btnok").vw.setWidth((int)((views.get("pnlmainsigbg2").vw.getWidth())-(2d / 100 * width) - ((69d / 100 * width))));
views.get("btnok").vw.setTop((int)((views.get("pnlfinishedanchor").vw.getTop() + views.get("pnlfinishedanchor").vw.getHeight())+(10d * scale)));

}
}