package bwsi.PumpOperations.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_waterbalance{

public static void LS_900x600_1(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
anywheresoftware.b4a.keywords.LayoutBuilder.scaleAll(views);
views.get("toolbar").vw.setTop((int)((0d * scale)));
if ((anywheresoftware.b4a.keywords.LayoutBuilder.getScreenSize()>6.5d)) { 
;
views.get("toolbar").vw.setHeight((int)((64d * scale)));
;}else{ 
;
if ((BA.ObjectToBoolean( String.valueOf(anywheresoftware.b4a.keywords.LayoutBuilder.isPortrait())))) { 
;
views.get("toolbar").vw.setHeight((int)((50d * scale)));
;}else{ 
;
views.get("toolbar").vw.setHeight((int)((42d * scale)));
;};
;};
views.get("pnlmain").vw.setWidth((int)((100d / 100 * width)));
views.get("pnlmain").vw.setHeight((int)((100d / 100 * height)-(views.get("toolbar").vw.getHeight())));
views.get("pnlmain").vw.setLeft((int)(0d));
views.get("pnlmain").vw.setTop((int)((views.get("toolbar").vw.getTop() + views.get("toolbar").vw.getHeight())));
views.get("pnlsupply").vw.setLeft((int)((3d * scale)));
views.get("pnlsupply").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(80d / 100 * width) - ((3d * scale))));
views.get("pnlsupply").vw.setTop((int)((1d / 100 * height)));
views.get("pnlsupply").vw.setHeight((int)((views.get("pnlmain").vw.getHeight())-(1d / 100 * height) - ((1d / 100 * height))));
views.get("pnlsupply").vw.setTop((int)((views.get("pnlmain").vw.getHeight())/2d - (views.get("pnlsupply").vw.getHeight() / 2)));
views.get("label1").vw.setLeft((int)((0.25d / 100 * width)));
views.get("label1").vw.setWidth((int)((views.get("pnlsupply").vw.getWidth())-(0.25d / 100 * width) - ((0.25d / 100 * width))));
views.get("label1").vw.setTop((int)((views.get("pnlsupply").vw.getHeight())/2d-(views.get("label1").vw.getHeight())));
views.get("lblsupply").vw.setLeft((int)((0.25d / 100 * width)));
views.get("lblsupply").vw.setWidth((int)((views.get("pnlsupply").vw.getWidth())-(0.25d / 100 * width) - ((0.25d / 100 * width))));
views.get("lblsupply").vw.setTop((int)((views.get("label1").vw.getTop() + views.get("label1").vw.getHeight())));
views.get("pnlauthcons").vw.setTop((int)((views.get("pnlsupply").vw.getTop())));
views.get("pnlauthcons").vw.setHeight((int)((views.get("pnlsupply").vw.getHeight())/2d));
views.get("pnlauthcons").vw.setLeft((int)((views.get("pnlsupply").vw.getLeft() + views.get("pnlsupply").vw.getWidth())));
views.get("pnlauthcons").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(60d / 100 * width) - ((views.get("pnlsupply").vw.getLeft() + views.get("pnlsupply").vw.getWidth()))));
views.get("label2").vw.setLeft((int)((0.25d / 100 * width)));
views.get("label2").vw.setWidth((int)((views.get("pnlauthcons").vw.getWidth())-(0.25d / 100 * width) - ((0.25d / 100 * width))));
views.get("label2").vw.setTop((int)((views.get("pnlauthcons").vw.getHeight())/2d-(views.get("label1").vw.getHeight())));
views.get("lblauthcons").vw.setLeft((int)((0.25d / 100 * width)));
views.get("lblauthcons").vw.setWidth((int)((views.get("pnlauthcons").vw.getWidth())-(0.25d / 100 * width) - ((0.25d / 100 * width))));
views.get("lblauthcons").vw.setTop((int)((views.get("label2").vw.getTop() + views.get("label2").vw.getHeight())));
views.get("pnlwaterlosses").vw.setTop((int)((views.get("pnlauthcons").vw.getTop() + views.get("pnlauthcons").vw.getHeight())));
views.get("pnlwaterlosses").vw.setHeight((int)((views.get("pnlsupply").vw.getHeight())/2d));
views.get("pnlwaterlosses").vw.setLeft((int)((views.get("pnlsupply").vw.getLeft() + views.get("pnlsupply").vw.getWidth())));
views.get("pnlwaterlosses").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(60d / 100 * width) - ((views.get("pnlsupply").vw.getLeft() + views.get("pnlsupply").vw.getWidth()))));
views.get("pnlbilledauthcons").vw.setTop((int)((views.get("pnlauthcons").vw.getTop())));
views.get("pnlbilledauthcons").vw.setHeight((int)((views.get("pnlauthcons").vw.getHeight())/2d));
views.get("pnlbilledauthcons").vw.setLeft((int)((views.get("pnlauthcons").vw.getLeft() + views.get("pnlauthcons").vw.getWidth())));
views.get("pnlbilledauthcons").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(40d / 100 * width) - ((views.get("pnlauthcons").vw.getLeft() + views.get("pnlauthcons").vw.getWidth()))));
views.get("pnlunbilledauthcons").vw.setTop((int)((views.get("pnlbilledauthcons").vw.getTop() + views.get("pnlbilledauthcons").vw.getHeight())));
views.get("pnlunbilledauthcons").vw.setHeight((int)((views.get("pnlauthcons").vw.getHeight())/2d));
views.get("pnlunbilledauthcons").vw.setLeft((int)((views.get("pnlauthcons").vw.getLeft() + views.get("pnlauthcons").vw.getWidth())));
views.get("pnlunbilledauthcons").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(40d / 100 * width) - ((views.get("pnlauthcons").vw.getLeft() + views.get("pnlauthcons").vw.getWidth()))));
views.get("pnlcomapplosses").vw.setTop((int)((views.get("pnlwaterlosses").vw.getTop())));
views.get("pnlcomapplosses").vw.setHeight((int)((views.get("pnlwaterlosses").vw.getHeight())/2d));
views.get("pnlcomapplosses").vw.setLeft((int)((views.get("pnlwaterlosses").vw.getLeft() + views.get("pnlwaterlosses").vw.getWidth())));
views.get("pnlcomapplosses").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(40d / 100 * width) - ((views.get("pnlwaterlosses").vw.getLeft() + views.get("pnlwaterlosses").vw.getWidth()))));
views.get("pnlrealphysicallosses").vw.setTop((int)((views.get("pnlcomapplosses").vw.getTop() + views.get("pnlcomapplosses").vw.getHeight())));
views.get("pnlrealphysicallosses").vw.setHeight((int)((views.get("pnlwaterlosses").vw.getHeight())/2d));
views.get("pnlrealphysicallosses").vw.setLeft((int)((views.get("pnlwaterlosses").vw.getLeft() + views.get("pnlwaterlosses").vw.getWidth())));
views.get("pnlrealphysicallosses").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(40d / 100 * width) - ((views.get("pnlwaterlosses").vw.getLeft() + views.get("pnlwaterlosses").vw.getWidth()))));
views.get("pnlbilledmetered").vw.setTop((int)((views.get("pnlbilledauthcons").vw.getTop())));
views.get("pnlbilledmetered").vw.setHeight((int)((views.get("pnlbilledauthcons").vw.getHeight())/2d));
views.get("pnlbilledmetered").vw.setLeft((int)((views.get("pnlbilledauthcons").vw.getLeft() + views.get("pnlbilledauthcons").vw.getWidth())));
views.get("pnlbilledmetered").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(20d / 100 * width) - ((views.get("pnlbilledauthcons").vw.getLeft() + views.get("pnlbilledauthcons").vw.getWidth()))));
views.get("pnlbilledunmetered").vw.setTop((int)((views.get("pnlbilledmetered").vw.getTop() + views.get("pnlbilledmetered").vw.getHeight())));
views.get("pnlbilledunmetered").vw.setHeight((int)((views.get("pnlbilledauthcons").vw.getHeight())/2d));
views.get("pnlbilledunmetered").vw.setLeft((int)((views.get("pnlbilledauthcons").vw.getLeft() + views.get("pnlbilledauthcons").vw.getWidth())));
views.get("pnlbilledunmetered").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(20d / 100 * width) - ((views.get("pnlbilledauthcons").vw.getLeft() + views.get("pnlbilledauthcons").vw.getWidth()))));
views.get("pnlunbilledmetered").vw.setTop((int)((views.get("pnlunbilledauthcons").vw.getTop())));
views.get("pnlunbilledmetered").vw.setHeight((int)((views.get("pnlbilledauthcons").vw.getHeight())/2d));
views.get("pnlunbilledmetered").vw.setLeft((int)((views.get("pnlunbilledauthcons").vw.getLeft() + views.get("pnlunbilledauthcons").vw.getWidth())));
views.get("pnlunbilledmetered").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(20d / 100 * width) - ((views.get("pnlunbilledauthcons").vw.getLeft() + views.get("pnlunbilledauthcons").vw.getWidth()))));
views.get("pnlunbilledunmetered").vw.setTop((int)((views.get("pnlunbilledmetered").vw.getTop() + views.get("pnlunbilledmetered").vw.getHeight())));
views.get("pnlunbilledunmetered").vw.setHeight((int)((views.get("pnlunbilledauthcons").vw.getHeight())/2d));
views.get("pnlunbilledunmetered").vw.setLeft((int)((views.get("pnlunbilledauthcons").vw.getLeft() + views.get("pnlunbilledauthcons").vw.getWidth())));
views.get("pnlunbilledunmetered").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(20d / 100 * width) - ((views.get("pnlunbilledauthcons").vw.getLeft() + views.get("pnlunbilledauthcons").vw.getWidth()))));
views.get("pnlunauthorized").vw.setTop((int)((views.get("pnlcomapplosses").vw.getTop())));
views.get("pnlunauthorized").vw.setHeight((int)((views.get("pnlcomapplosses").vw.getHeight())/2d));
views.get("pnlunauthorized").vw.setLeft((int)((views.get("pnlcomapplosses").vw.getLeft() + views.get("pnlcomapplosses").vw.getWidth())));
views.get("pnlunauthorized").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(20d / 100 * width) - ((views.get("pnlcomapplosses").vw.getLeft() + views.get("pnlcomapplosses").vw.getWidth()))));
views.get("pnlmeteringinaccuracies").vw.setTop((int)((views.get("pnlunauthorized").vw.getTop() + views.get("pnlunauthorized").vw.getHeight())));
views.get("pnlmeteringinaccuracies").vw.setHeight((int)((views.get("pnlcomapplosses").vw.getHeight())/2d));
views.get("pnlmeteringinaccuracies").vw.setLeft((int)((views.get("pnlcomapplosses").vw.getLeft() + views.get("pnlcomapplosses").vw.getWidth())));
views.get("pnlmeteringinaccuracies").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(20d / 100 * width) - ((views.get("pnlcomapplosses").vw.getLeft() + views.get("pnlcomapplosses").vw.getWidth()))));
views.get("pnlaccountedleakage").vw.setTop((int)((views.get("pnlrealphysicallosses").vw.getTop())));
views.get("pnlaccountedleakage").vw.setHeight((int)((views.get("pnlrealphysicallosses").vw.getHeight())/2d));
views.get("pnlaccountedleakage").vw.setLeft((int)((views.get("pnlrealphysicallosses").vw.getLeft() + views.get("pnlrealphysicallosses").vw.getWidth())));
views.get("pnlaccountedleakage").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(20d / 100 * width) - ((views.get("pnlrealphysicallosses").vw.getLeft() + views.get("pnlrealphysicallosses").vw.getWidth()))));
views.get("pnlunaccountedleakage").vw.setTop((int)((views.get("pnlaccountedleakage").vw.getTop() + views.get("pnlaccountedleakage").vw.getHeight())));
views.get("pnlunaccountedleakage").vw.setHeight((int)((views.get("pnlrealphysicallosses").vw.getHeight())/2d));
views.get("pnlunaccountedleakage").vw.setLeft((int)((views.get("pnlrealphysicallosses").vw.getLeft() + views.get("pnlrealphysicallosses").vw.getWidth())));
views.get("pnlunaccountedleakage").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(20d / 100 * width) - ((views.get("pnlrealphysicallosses").vw.getLeft() + views.get("pnlrealphysicallosses").vw.getWidth()))));
views.get("pnlrevenue").vw.setTop((int)((views.get("pnlbilledmetered").vw.getTop())));
views.get("pnlrevenue").vw.setHeight((int)((views.get("pnlbilledauthcons").vw.getHeight())));
views.get("pnlrevenue").vw.setLeft((int)((views.get("pnlbilledmetered").vw.getLeft() + views.get("pnlbilledmetered").vw.getWidth())));
views.get("pnlrevenue").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(3d * scale) - ((views.get("pnlbilledmetered").vw.getLeft() + views.get("pnlbilledmetered").vw.getWidth()))));
views.get("pnlnrw").vw.setTop((int)((views.get("pnlrevenue").vw.getTop() + views.get("pnlrevenue").vw.getHeight())));
views.get("pnlnrw").vw.setHeight((int)((views.get("pnlsupply").vw.getHeight())-(views.get("pnlrevenue").vw.getHeight())));
views.get("pnlnrw").vw.setLeft((int)((views.get("pnlunbilledmetered").vw.getLeft() + views.get("pnlunbilledmetered").vw.getWidth())));
views.get("pnlnrw").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(3d * scale) - ((views.get("pnlunbilledmetered").vw.getLeft() + views.get("pnlunbilledmetered").vw.getWidth()))));

}
public static void LS_general(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
anywheresoftware.b4a.keywords.LayoutBuilder.scaleAll(views);
views.get("toolbar").vw.setTop((int)((0d * scale)));
if ((anywheresoftware.b4a.keywords.LayoutBuilder.getScreenSize()>6.5d)) { 
;
views.get("toolbar").vw.setHeight((int)((64d * scale)));
;}else{ 
;
if ((BA.ObjectToBoolean( String.valueOf(anywheresoftware.b4a.keywords.LayoutBuilder.isPortrait())))) { 
;
views.get("toolbar").vw.setHeight((int)((50d * scale)));
;}else{ 
;
views.get("toolbar").vw.setHeight((int)((42d * scale)));
;};
;};
views.get("pnlmain").vw.setWidth((int)((100d / 100 * width)));
views.get("pnlmain").vw.setHeight((int)((100d / 100 * height)-(views.get("toolbar").vw.getHeight())));
views.get("pnlmain").vw.setLeft((int)(0d));
views.get("pnlmain").vw.setTop((int)((views.get("toolbar").vw.getTop() + views.get("toolbar").vw.getHeight())));
views.get("pnlsupply").vw.setLeft((int)((3d * scale)));
views.get("pnlsupply").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(80d / 100 * width) - ((3d * scale))));
views.get("pnlsupply").vw.setTop((int)((1d / 100 * height)));
views.get("pnlsupply").vw.setHeight((int)((views.get("pnlmain").vw.getHeight())-(1d / 100 * height) - ((1d / 100 * height))));
views.get("pnlsupply").vw.setTop((int)((views.get("pnlmain").vw.getHeight())/2d - (views.get("pnlsupply").vw.getHeight() / 2)));
views.get("label1").vw.setLeft((int)((0.25d / 100 * width)));
views.get("label1").vw.setWidth((int)((views.get("pnlsupply").vw.getWidth())-(0.25d / 100 * width) - ((0.25d / 100 * width))));
views.get("label1").vw.setTop((int)((views.get("pnlsupply").vw.getHeight())/2d-(views.get("label1").vw.getHeight())));
views.get("lblsupply").vw.setLeft((int)((0.25d / 100 * width)));
views.get("lblsupply").vw.setWidth((int)((views.get("pnlsupply").vw.getWidth())-(0.25d / 100 * width) - ((0.25d / 100 * width))));
views.get("lblsupply").vw.setTop((int)((views.get("label1").vw.getTop() + views.get("label1").vw.getHeight())));
views.get("pnlauthcons").vw.setTop((int)((views.get("pnlsupply").vw.getTop())));
views.get("pnlauthcons").vw.setHeight((int)((views.get("pnlsupply").vw.getHeight())/2d));
views.get("pnlauthcons").vw.setLeft((int)((views.get("pnlsupply").vw.getLeft() + views.get("pnlsupply").vw.getWidth())));
views.get("pnlauthcons").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(60d / 100 * width) - ((views.get("pnlsupply").vw.getLeft() + views.get("pnlsupply").vw.getWidth()))));
views.get("label2").vw.setLeft((int)((0.25d / 100 * width)));
views.get("label2").vw.setWidth((int)((views.get("pnlauthcons").vw.getWidth())-(0.25d / 100 * width) - ((0.25d / 100 * width))));
views.get("label2").vw.setTop((int)((views.get("pnlauthcons").vw.getHeight())/2d-(views.get("label1").vw.getHeight())));
views.get("lblauthcons").vw.setLeft((int)((0.25d / 100 * width)));
views.get("lblauthcons").vw.setWidth((int)((views.get("pnlauthcons").vw.getWidth())-(0.25d / 100 * width) - ((0.25d / 100 * width))));
views.get("lblauthcons").vw.setTop((int)((views.get("label2").vw.getTop() + views.get("label2").vw.getHeight())));
views.get("pnlwaterlosses").vw.setTop((int)((views.get("pnlauthcons").vw.getTop() + views.get("pnlauthcons").vw.getHeight())));
views.get("pnlwaterlosses").vw.setHeight((int)((views.get("pnlsupply").vw.getHeight())/2d));
views.get("pnlwaterlosses").vw.setLeft((int)((views.get("pnlsupply").vw.getLeft() + views.get("pnlsupply").vw.getWidth())));
views.get("pnlwaterlosses").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(60d / 100 * width) - ((views.get("pnlsupply").vw.getLeft() + views.get("pnlsupply").vw.getWidth()))));
views.get("pnlbilledauthcons").vw.setTop((int)((views.get("pnlauthcons").vw.getTop())));
views.get("pnlbilledauthcons").vw.setHeight((int)((views.get("pnlauthcons").vw.getHeight())/2d));
views.get("pnlbilledauthcons").vw.setLeft((int)((views.get("pnlauthcons").vw.getLeft() + views.get("pnlauthcons").vw.getWidth())));
views.get("pnlbilledauthcons").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(40d / 100 * width) - ((views.get("pnlauthcons").vw.getLeft() + views.get("pnlauthcons").vw.getWidth()))));
views.get("pnlunbilledauthcons").vw.setTop((int)((views.get("pnlbilledauthcons").vw.getTop() + views.get("pnlbilledauthcons").vw.getHeight())));
views.get("pnlunbilledauthcons").vw.setHeight((int)((views.get("pnlauthcons").vw.getHeight())/2d));
views.get("pnlunbilledauthcons").vw.setLeft((int)((views.get("pnlauthcons").vw.getLeft() + views.get("pnlauthcons").vw.getWidth())));
views.get("pnlunbilledauthcons").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(40d / 100 * width) - ((views.get("pnlauthcons").vw.getLeft() + views.get("pnlauthcons").vw.getWidth()))));
views.get("pnlcomapplosses").vw.setTop((int)((views.get("pnlwaterlosses").vw.getTop())));
views.get("pnlcomapplosses").vw.setHeight((int)((views.get("pnlwaterlosses").vw.getHeight())/2d));
views.get("pnlcomapplosses").vw.setLeft((int)((views.get("pnlwaterlosses").vw.getLeft() + views.get("pnlwaterlosses").vw.getWidth())));
views.get("pnlcomapplosses").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(40d / 100 * width) - ((views.get("pnlwaterlosses").vw.getLeft() + views.get("pnlwaterlosses").vw.getWidth()))));
views.get("pnlrealphysicallosses").vw.setTop((int)((views.get("pnlcomapplosses").vw.getTop() + views.get("pnlcomapplosses").vw.getHeight())));
views.get("pnlrealphysicallosses").vw.setHeight((int)((views.get("pnlwaterlosses").vw.getHeight())/2d));
views.get("pnlrealphysicallosses").vw.setLeft((int)((views.get("pnlwaterlosses").vw.getLeft() + views.get("pnlwaterlosses").vw.getWidth())));
views.get("pnlrealphysicallosses").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(40d / 100 * width) - ((views.get("pnlwaterlosses").vw.getLeft() + views.get("pnlwaterlosses").vw.getWidth()))));
views.get("pnlbilledmetered").vw.setTop((int)((views.get("pnlbilledauthcons").vw.getTop())));
views.get("pnlbilledmetered").vw.setHeight((int)((views.get("pnlbilledauthcons").vw.getHeight())/2d));
views.get("pnlbilledmetered").vw.setLeft((int)((views.get("pnlbilledauthcons").vw.getLeft() + views.get("pnlbilledauthcons").vw.getWidth())));
views.get("pnlbilledmetered").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(20d / 100 * width) - ((views.get("pnlbilledauthcons").vw.getLeft() + views.get("pnlbilledauthcons").vw.getWidth()))));
views.get("pnlbilledunmetered").vw.setTop((int)((views.get("pnlbilledmetered").vw.getTop() + views.get("pnlbilledmetered").vw.getHeight())));
views.get("pnlbilledunmetered").vw.setHeight((int)((views.get("pnlbilledauthcons").vw.getHeight())/2d));
views.get("pnlbilledunmetered").vw.setLeft((int)((views.get("pnlbilledauthcons").vw.getLeft() + views.get("pnlbilledauthcons").vw.getWidth())));
views.get("pnlbilledunmetered").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(20d / 100 * width) - ((views.get("pnlbilledauthcons").vw.getLeft() + views.get("pnlbilledauthcons").vw.getWidth()))));
views.get("pnlunbilledmetered").vw.setTop((int)((views.get("pnlunbilledauthcons").vw.getTop())));
views.get("pnlunbilledmetered").vw.setHeight((int)((views.get("pnlbilledauthcons").vw.getHeight())/2d));
views.get("pnlunbilledmetered").vw.setLeft((int)((views.get("pnlunbilledauthcons").vw.getLeft() + views.get("pnlunbilledauthcons").vw.getWidth())));
views.get("pnlunbilledmetered").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(20d / 100 * width) - ((views.get("pnlunbilledauthcons").vw.getLeft() + views.get("pnlunbilledauthcons").vw.getWidth()))));
views.get("pnlunbilledunmetered").vw.setTop((int)((views.get("pnlunbilledmetered").vw.getTop() + views.get("pnlunbilledmetered").vw.getHeight())));
views.get("pnlunbilledunmetered").vw.setHeight((int)((views.get("pnlunbilledauthcons").vw.getHeight())/2d));
views.get("pnlunbilledunmetered").vw.setLeft((int)((views.get("pnlunbilledauthcons").vw.getLeft() + views.get("pnlunbilledauthcons").vw.getWidth())));
views.get("pnlunbilledunmetered").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(20d / 100 * width) - ((views.get("pnlunbilledauthcons").vw.getLeft() + views.get("pnlunbilledauthcons").vw.getWidth()))));
views.get("pnlunauthorized").vw.setTop((int)((views.get("pnlcomapplosses").vw.getTop())));
views.get("pnlunauthorized").vw.setHeight((int)((views.get("pnlcomapplosses").vw.getHeight())/2d));
views.get("pnlunauthorized").vw.setLeft((int)((views.get("pnlcomapplosses").vw.getLeft() + views.get("pnlcomapplosses").vw.getWidth())));
views.get("pnlunauthorized").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(20d / 100 * width) - ((views.get("pnlcomapplosses").vw.getLeft() + views.get("pnlcomapplosses").vw.getWidth()))));
views.get("pnlmeteringinaccuracies").vw.setTop((int)((views.get("pnlunauthorized").vw.getTop() + views.get("pnlunauthorized").vw.getHeight())));
views.get("pnlmeteringinaccuracies").vw.setHeight((int)((views.get("pnlcomapplosses").vw.getHeight())/2d));
views.get("pnlmeteringinaccuracies").vw.setLeft((int)((views.get("pnlcomapplosses").vw.getLeft() + views.get("pnlcomapplosses").vw.getWidth())));
views.get("pnlmeteringinaccuracies").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(20d / 100 * width) - ((views.get("pnlcomapplosses").vw.getLeft() + views.get("pnlcomapplosses").vw.getWidth()))));
views.get("pnlaccountedleakage").vw.setTop((int)((views.get("pnlrealphysicallosses").vw.getTop())));
views.get("pnlaccountedleakage").vw.setHeight((int)((views.get("pnlrealphysicallosses").vw.getHeight())/2d));
views.get("pnlaccountedleakage").vw.setLeft((int)((views.get("pnlrealphysicallosses").vw.getLeft() + views.get("pnlrealphysicallosses").vw.getWidth())));
views.get("pnlaccountedleakage").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(20d / 100 * width) - ((views.get("pnlrealphysicallosses").vw.getLeft() + views.get("pnlrealphysicallosses").vw.getWidth()))));
views.get("pnlunaccountedleakage").vw.setTop((int)((views.get("pnlaccountedleakage").vw.getTop() + views.get("pnlaccountedleakage").vw.getHeight())));
views.get("pnlunaccountedleakage").vw.setHeight((int)((views.get("pnlrealphysicallosses").vw.getHeight())/2d));
views.get("pnlunaccountedleakage").vw.setLeft((int)((views.get("pnlrealphysicallosses").vw.getLeft() + views.get("pnlrealphysicallosses").vw.getWidth())));
views.get("pnlunaccountedleakage").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(20d / 100 * width) - ((views.get("pnlrealphysicallosses").vw.getLeft() + views.get("pnlrealphysicallosses").vw.getWidth()))));
views.get("pnlrevenue").vw.setTop((int)((views.get("pnlbilledmetered").vw.getTop())));
views.get("pnlrevenue").vw.setHeight((int)((views.get("pnlbilledauthcons").vw.getHeight())));
views.get("pnlrevenue").vw.setLeft((int)((views.get("pnlbilledmetered").vw.getLeft() + views.get("pnlbilledmetered").vw.getWidth())));
views.get("pnlrevenue").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(3d * scale) - ((views.get("pnlbilledmetered").vw.getLeft() + views.get("pnlbilledmetered").vw.getWidth()))));
views.get("pnlnrw").vw.setTop((int)((views.get("pnlrevenue").vw.getTop() + views.get("pnlrevenue").vw.getHeight())));
views.get("pnlnrw").vw.setHeight((int)((views.get("pnlsupply").vw.getHeight())-(views.get("pnlrevenue").vw.getHeight())));
views.get("pnlnrw").vw.setLeft((int)((views.get("pnlunbilledmetered").vw.getLeft() + views.get("pnlunbilledmetered").vw.getWidth())));
views.get("pnlnrw").vw.setWidth((int)((views.get("pnlmain").vw.getWidth())-(3d * scale) - ((views.get("pnlunbilledmetered").vw.getLeft() + views.get("pnlunbilledmetered").vw.getWidth()))));

}
}